FROM golang:1.25-alpine AS build
LABEL org.opencontainers.image.source=https://github.com/tlalocweb/hulation
LABEL org.opencontainers.image.description="Hula - the modern web server for DM and CDP services"
LABEL org.opencontainers.image.licenses=Apache-2.0

RUN apk add --no-cache musl-dev gcc
ENV CGO_ENABLED=1

ADD hulation /src/hulation
ADD clickhouse /src/clickhouse
WORKDIR /src/hulation

ARG hulaversion=notset
ARG hulabuilddate=notset
RUN go build -ldflags "-X github.com/tlalocweb/hulation/config.Version=${hulaversion} -X github.com/tlalocweb/hulation/config.BuildDate=${hulabuilddate}" -o hula .
RUN go build -ldflags "-X github.com/tlalocweb/hulation/config.Version=${hulaversion} -X github.com/tlalocweb/hulation/config.BuildDate=${hulabuilddate}" -o hulactl ./model/tools/hulactl

FROM alpine:3.19
RUN mkdir -p /etc/hula /var/hula /hula /var/hula/public /var/hula/scripts
ADD hulation/docker-example-config.yaml /etc/hula/config.yaml
COPY --from=build /src/hulation/hula /hula/hula
COPY --from=build /src/hulation/hulactl /hula/hulactl
COPY --from=build /src/hulation/scripts /hula/scripts
ENTRYPOINT [ "/hula/hula", "-config", "/etc/hula/config.yaml" ]
