// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/apispec/v1/reports/reports.proto

// ReportsService — scheduled email-report CRUD + preview +
// send-now + run history.
//
// A ScheduledReport is a persistent blueprint: cron expression,
// timezone, recipients, analytics filter preset, and a template
// variant ('summary' | 'detailed'). The Phase-3.5 dispatcher
// goroutine reads all enabled reports on boot, computes
// `next_fire_at` per cron+tz, and fires them on a 1-minute ticker.
//
// Preview returns rendered HTML so the admin UI can iframe-preview
// before saving. SendNow bypasses the schedule and enqueues an
// immediate render+send via the same code path.
//
// All writes require server.<id>.admin. Reads require
// server.<id>.analytics.read so non-admins can at least see what
// they'd receive in their inbox.

package reportsspec

import (
	_ "github.com/tlalocweb/hulation/protoext/hula/auth"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TemplateVariant discriminates email body style. 'summary' is the
// lightweight KPI-cards-only version; 'detailed' includes a main
// timeline chart + top-N tables.
type TemplateVariant int32

const (
	TemplateVariant_TEMPLATE_VARIANT_UNSPECIFIED TemplateVariant = 0
	TemplateVariant_TEMPLATE_VARIANT_SUMMARY     TemplateVariant = 1
	TemplateVariant_TEMPLATE_VARIANT_DETAILED    TemplateVariant = 2
)

// Enum value maps for TemplateVariant.
var (
	TemplateVariant_name = map[int32]string{
		0: "TEMPLATE_VARIANT_UNSPECIFIED",
		1: "TEMPLATE_VARIANT_SUMMARY",
		2: "TEMPLATE_VARIANT_DETAILED",
	}
	TemplateVariant_value = map[string]int32{
		"TEMPLATE_VARIANT_UNSPECIFIED": 0,
		"TEMPLATE_VARIANT_SUMMARY":     1,
		"TEMPLATE_VARIANT_DETAILED":    2,
	}
)

func (x TemplateVariant) Enum() *TemplateVariant {
	p := new(TemplateVariant)
	*p = x
	return p
}

func (x TemplateVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_apispec_v1_reports_reports_proto_enumTypes[0].Descriptor()
}

func (TemplateVariant) Type() protoreflect.EnumType {
	return &file_pkg_apispec_v1_reports_reports_proto_enumTypes[0]
}

func (x TemplateVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateVariant.Descriptor instead.
func (TemplateVariant) EnumDescriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{0}
}

type ScheduledReport struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// RFC 5545 style cron expression. Parsed by robfig/cron v3 —
	// supports standard five-field syntax (min hr dom mon dow).
	Cron string `protobuf:"bytes,4,opt,name=cron,proto3" json:"cron,omitempty"`
	// IANA timezone (e.g., "America/Los_Angeles"). Required; the
	// dispatcher refuses to fire reports with an empty or invalid tz.
	Timezone        string          `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Recipients      []string        `protobuf:"bytes,6,rep,name=recipients,proto3" json:"recipients,omitempty"`
	TemplateVariant TemplateVariant `protobuf:"varint,7,opt,name=template_variant,json=templateVariant,proto3,enum=hulation.v1.reports.TemplateVariant" json:"template_variant,omitempty"`
	// Filter preset saved from the UI's filter bar state. The
	// dispatcher applies these when rendering the report body.
	Filters *Filters `protobuf:"bytes,8,opt,name=filters,proto3" json:"filters,omitempty"`
	Enabled bool     `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Server-populated:
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	NextFireAt    *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=next_fire_at,json=nextFireAt,proto3" json:"next_fire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledReport) Reset() {
	*x = ScheduledReport{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledReport) ProtoMessage() {}

func (x *ScheduledReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledReport.ProtoReflect.Descriptor instead.
func (*ScheduledReport) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduledReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduledReport) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ScheduledReport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduledReport) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *ScheduledReport) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ScheduledReport) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *ScheduledReport) GetTemplateVariant() TemplateVariant {
	if x != nil {
		return x.TemplateVariant
	}
	return TemplateVariant_TEMPLATE_VARIANT_UNSPECIFIED
}

func (x *ScheduledReport) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ScheduledReport) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScheduledReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScheduledReport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ScheduledReport) GetNextFireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextFireAt
	}
	return nil
}

type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Report        *ScheduledReport       `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReportRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateReportRequest) GetReport() *ScheduledReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type UpdateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Report        *ScheduledReport       `protobuf:"bytes,3,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReportRequest) Reset() {
	*x = UpdateReportRequest{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReportRequest) ProtoMessage() {}

func (x *UpdateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateReportRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *UpdateReportRequest) GetReport() *ScheduledReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type DeleteReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReportRequest) Reset() {
	*x = DeleteReportRequest{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReportRequest) ProtoMessage() {}

func (x *DeleteReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteReportRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type DeleteReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReportResponse) Reset() {
	*x = DeleteReportResponse{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReportResponse) ProtoMessage() {}

func (x *DeleteReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReportResponse.ProtoReflect.Descriptor instead.
func (*DeleteReportResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReportResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{5}
}

func (x *ListReportsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ListReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ScheduledReport     `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{6}
}

func (x *ListReportsResponse) GetReports() []*ScheduledReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{7}
}

func (x *GetReportRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type PreviewReportRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReportId string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// Optional override filters. When empty the stored report's
	// filter preset is used.
	Filters       *Filters `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewReportRequest) Reset() {
	*x = PreviewReportRequest{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewReportRequest) ProtoMessage() {}

func (x *PreviewReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewReportRequest.ProtoReflect.Descriptor instead.
func (*PreviewReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{8}
}

func (x *PreviewReportRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *PreviewReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *PreviewReportRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PreviewReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Html          string                 `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewReportResponse) Reset() {
	*x = PreviewReportResponse{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewReportResponse) ProtoMessage() {}

func (x *PreviewReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewReportResponse.ProtoReflect.Descriptor instead.
func (*PreviewReportResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{9}
}

func (x *PreviewReportResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *PreviewReportResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SendNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNowRequest) Reset() {
	*x = SendNowRequest{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNowRequest) ProtoMessage() {}

func (x *SendNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNowRequest.ProtoReflect.Descriptor instead.
func (*SendNowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{10}
}

func (x *SendNowRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SendNowRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type SendNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNowResponse) Reset() {
	*x = SendNowResponse{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNowResponse) ProtoMessage() {}

func (x *SendNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNowResponse.ProtoReflect.Descriptor instead.
func (*SendNowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{11}
}

func (x *SendNowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{12}
}

func (x *ListRunsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListRunsRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*ReportRun           `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{13}
}

func (x *ListRunsResponse) GetRuns() []*ReportRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

// ReportRun — one dispatch attempt. Retries live in `attempt`;
// status transitions success / failed / retrying.
type ReportRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // 'success' | 'failed' | 'retrying'
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Recipients    []string               `protobuf:"bytes,8,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRun) Reset() {
	*x = ReportRun{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRun) ProtoMessage() {}

func (x *ReportRun) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRun.ProtoReflect.Descriptor instead.
func (*ReportRun) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{14}
}

func (x *ReportRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportRun) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReportRun) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ReportRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportRun) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ReportRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportRun) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

// Filters mirror — see goals.proto for rationale.
type Filters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerIds     []string               `protobuf:"bytes,1,rep,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Granularity   string                 `protobuf:"bytes,4,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Compare       string                 `protobuf:"bytes,5,opt,name=compare,proto3" json:"compare,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Device        string                 `protobuf:"bytes,7,opt,name=device,proto3" json:"device,omitempty"`
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	Path          string                 `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	EventCode     string                 `protobuf:"bytes,10,opt,name=event_code,json=eventCode,proto3" json:"event_code,omitempty"`
	Goal          string                 `protobuf:"bytes,11,opt,name=goal,proto3" json:"goal,omitempty"`
	Browser       string                 `protobuf:"bytes,12,opt,name=browser,proto3" json:"browser,omitempty"`
	Os            string                 `protobuf:"bytes,13,opt,name=os,proto3" json:"os,omitempty"`
	Channel       string                 `protobuf:"bytes,14,opt,name=channel,proto3" json:"channel,omitempty"`
	UtmSource     string                 `protobuf:"bytes,15,opt,name=utm_source,json=utmSource,proto3" json:"utm_source,omitempty"`
	UtmMedium     string                 `protobuf:"bytes,16,opt,name=utm_medium,json=utmMedium,proto3" json:"utm_medium,omitempty"`
	UtmCampaign   string                 `protobuf:"bytes,17,opt,name=utm_campaign,json=utmCampaign,proto3" json:"utm_campaign,omitempty"`
	Region        string                 `protobuf:"bytes,18,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,19,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_reports_reports_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP(), []int{15}
}

func (x *Filters) GetServerIds() []string {
	if x != nil {
		return x.ServerIds
	}
	return nil
}

func (x *Filters) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Filters) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Filters) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *Filters) GetCompare() string {
	if x != nil {
		return x.Compare
	}
	return ""
}

func (x *Filters) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Filters) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Filters) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Filters) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Filters) GetEventCode() string {
	if x != nil {
		return x.EventCode
	}
	return ""
}

func (x *Filters) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Filters) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Filters) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Filters) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Filters) GetUtmSource() string {
	if x != nil {
		return x.UtmSource
	}
	return ""
}

func (x *Filters) GetUtmMedium() string {
	if x != nil {
		return x.UtmMedium
	}
	return ""
}

func (x *Filters) GetUtmCampaign() string {
	if x != nil {
		return x.UtmCampaign
	}
	return ""
}

func (x *Filters) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Filters) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

var File_pkg_apispec_v1_reports_reports_proto protoreflect.FileDescriptor

const file_pkg_apispec_v1_reports_reports_proto_rawDesc = "" +
	"\n" +
	"$pkg/apispec/v1/reports/reports.proto\x12\x13hulation.v1.reports\x1a\x1cgoogle/api/annotations.proto\x1a\x1ahula/auth/permission.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x03\n" +
	"\x0fScheduledReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04cron\x18\x04 \x01(\tR\x04cron\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12\x1e\n" +
	"\n" +
	"recipients\x18\x06 \x03(\tR\n" +
	"recipients\x12O\n" +
	"\x10template_variant\x18\a \x01(\x0e2$.hulation.v1.reports.TemplateVariantR\x0ftemplateVariant\x126\n" +
	"\afilters\x18\b \x01(\v2\x1c.hulation.v1.reports.FiltersR\afilters\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\fnext_fire_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextFireAt\"p\n" +
	"\x13CreateReportRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12<\n" +
	"\x06report\x18\x02 \x01(\v2$.hulation.v1.reports.ScheduledReportR\x06report\"\x8d\x01\n" +
	"\x13UpdateReportRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12<\n" +
	"\x06report\x18\x03 \x01(\v2$.hulation.v1.reports.ScheduledReportR\x06report\"O\n" +
	"\x13DeleteReportRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"&\n" +
	"\x14DeleteReportResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"1\n" +
	"\x12ListReportsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"U\n" +
	"\x13ListReportsResponse\x12>\n" +
	"\areports\x18\x01 \x03(\v2$.hulation.v1.reports.ScheduledReportR\areports\"L\n" +
	"\x10GetReportRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"\x88\x01\n" +
	"\x14PreviewReportRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x126\n" +
	"\afilters\x18\x03 \x01(\v2\x1c.hulation.v1.reports.FiltersR\afilters\"E\n" +
	"\x15PreviewReportResponse\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"J\n" +
	"\x0eSendNowRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"(\n" +
	"\x0fSendNowResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"a\n" +
	"\x0fListRunsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"F\n" +
	"\x10ListRunsResponse\x122\n" +
	"\x04runs\x18\x01 \x03(\v2\x1e.hulation.v1.reports.ReportRunR\x04runs\"\x98\x02\n" +
	"\tReportRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"recipients\x18\b \x03(\tR\n" +
	"recipients\"\xea\x03\n" +
	"\aFilters\x12\x1d\n" +
	"\n" +
	"server_ids\x18\x01 \x03(\tR\tserverIds\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12 \n" +
	"\vgranularity\x18\x04 \x01(\tR\vgranularity\x12\x18\n" +
	"\acompare\x18\x05 \x01(\tR\acompare\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x16\n" +
	"\x06device\x18\a \x01(\tR\x06device\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"event_code\x18\n" +
	" \x01(\tR\teventCode\x12\x12\n" +
	"\x04goal\x18\v \x01(\tR\x04goal\x12\x18\n" +
	"\abrowser\x18\f \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\r \x01(\tR\x02os\x12\x18\n" +
	"\achannel\x18\x0e \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"utm_source\x18\x0f \x01(\tR\tutmSource\x12\x1d\n" +
	"\n" +
	"utm_medium\x18\x10 \x01(\tR\tutmMedium\x12!\n" +
	"\futm_campaign\x18\x11 \x01(\tR\vutmCampaign\x12\x16\n" +
	"\x06region\x18\x12 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x13 \x01(\tR\x04city*p\n" +
	"\x0fTemplateVariant\x12 \n" +
	"\x1cTEMPLATE_VARIANT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TEMPLATE_VARIANT_SUMMARY\x10\x01\x12\x1d\n" +
	"\x19TEMPLATE_VARIANT_DETAILED\x10\x022\xba\v\n" +
	"\x0eReportsService\x12\xa9\x01\n" +
	"\fCreateReport\x12(.hulation.v1.reports.CreateReportRequest\x1a$.hulation.v1.reports.ScheduledReport\"Iҵ\x18\x1a\n" +
	"\x18server.{server_id}.admin\x82\xd3\xe4\x93\x02%:\x06report\"\x1b/api/v1/reports/{server_id}\x12\xb5\x01\n" +
	"\fUpdateReport\x12(.hulation.v1.reports.UpdateReportRequest\x1a$.hulation.v1.reports.ScheduledReport\"Uҵ\x18\x1a\n" +
	"\x18server.{server_id}.admin\x82\xd3\xe4\x93\x021:\x06report2'/api/v1/reports/{server_id}/{report_id}\x12\xb2\x01\n" +
	"\fDeleteReport\x12(.hulation.v1.reports.DeleteReportRequest\x1a).hulation.v1.reports.DeleteReportResponse\"Mҵ\x18\x1a\n" +
	"\x18server.{server_id}.admin\x82\xd3\xe4\x93\x02)*'/api/v1/reports/{server_id}/{report_id}\x12\xac\x01\n" +
	"\vListReports\x12'.hulation.v1.reports.ListReportsRequest\x1a(.hulation.v1.reports.ListReportsResponse\"Jҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/reports/{server_id}\x12\xb0\x01\n" +
	"\tGetReport\x12%.hulation.v1.reports.GetReportRequest\x1a$.hulation.v1.reports.ScheduledReport\"Vҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02)\x12'/api/v1/reports/{server_id}/{report_id}\x12\xc6\x01\n" +
	"\rPreviewReport\x12).hulation.v1.reports.PreviewReportRequest\x1a*.hulation.v1.reports.PreviewReportResponse\"^ҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x021\"//api/v1/reports/{server_id}/{report_id}/preview\x12\xac\x01\n" +
	"\aSendNow\x12#.hulation.v1.reports.SendNowRequest\x1a$.hulation.v1.reports.SendNowResponse\"Vҵ\x18\x1a\n" +
	"\x18server.{server_id}.admin\x82\xd3\xe4\x93\x022\"0/api/v1/reports/{server_id}/{report_id}/send-now\x12\xb4\x01\n" +
	"\bListRuns\x12$.hulation.v1.reports.ListRunsRequest\x1a%.hulation.v1.reports.ListRunsResponse\"[ҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02.\x12,/api/v1/reports/{server_id}/{report_id}/runsBBZ@github.com/tlalocweb/hulation/pkg/apispec/v1/reports;reportsspecb\x06proto3"

var (
	file_pkg_apispec_v1_reports_reports_proto_rawDescOnce sync.Once
	file_pkg_apispec_v1_reports_reports_proto_rawDescData []byte
)

func file_pkg_apispec_v1_reports_reports_proto_rawDescGZIP() []byte {
	file_pkg_apispec_v1_reports_reports_proto_rawDescOnce.Do(func() {
		file_pkg_apispec_v1_reports_reports_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_reports_reports_proto_rawDesc), len(file_pkg_apispec_v1_reports_reports_proto_rawDesc)))
	})
	return file_pkg_apispec_v1_reports_reports_proto_rawDescData
}

var file_pkg_apispec_v1_reports_reports_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_apispec_v1_reports_reports_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_apispec_v1_reports_reports_proto_goTypes = []any{
	(TemplateVariant)(0),          // 0: hulation.v1.reports.TemplateVariant
	(*ScheduledReport)(nil),       // 1: hulation.v1.reports.ScheduledReport
	(*CreateReportRequest)(nil),   // 2: hulation.v1.reports.CreateReportRequest
	(*UpdateReportRequest)(nil),   // 3: hulation.v1.reports.UpdateReportRequest
	(*DeleteReportRequest)(nil),   // 4: hulation.v1.reports.DeleteReportRequest
	(*DeleteReportResponse)(nil),  // 5: hulation.v1.reports.DeleteReportResponse
	(*ListReportsRequest)(nil),    // 6: hulation.v1.reports.ListReportsRequest
	(*ListReportsResponse)(nil),   // 7: hulation.v1.reports.ListReportsResponse
	(*GetReportRequest)(nil),      // 8: hulation.v1.reports.GetReportRequest
	(*PreviewReportRequest)(nil),  // 9: hulation.v1.reports.PreviewReportRequest
	(*PreviewReportResponse)(nil), // 10: hulation.v1.reports.PreviewReportResponse
	(*SendNowRequest)(nil),        // 11: hulation.v1.reports.SendNowRequest
	(*SendNowResponse)(nil),       // 12: hulation.v1.reports.SendNowResponse
	(*ListRunsRequest)(nil),       // 13: hulation.v1.reports.ListRunsRequest
	(*ListRunsResponse)(nil),      // 14: hulation.v1.reports.ListRunsResponse
	(*ReportRun)(nil),             // 15: hulation.v1.reports.ReportRun
	(*Filters)(nil),               // 16: hulation.v1.reports.Filters
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_pkg_apispec_v1_reports_reports_proto_depIdxs = []int32{
	0,  // 0: hulation.v1.reports.ScheduledReport.template_variant:type_name -> hulation.v1.reports.TemplateVariant
	16, // 1: hulation.v1.reports.ScheduledReport.filters:type_name -> hulation.v1.reports.Filters
	17, // 2: hulation.v1.reports.ScheduledReport.created_at:type_name -> google.protobuf.Timestamp
	17, // 3: hulation.v1.reports.ScheduledReport.updated_at:type_name -> google.protobuf.Timestamp
	17, // 4: hulation.v1.reports.ScheduledReport.next_fire_at:type_name -> google.protobuf.Timestamp
	1,  // 5: hulation.v1.reports.CreateReportRequest.report:type_name -> hulation.v1.reports.ScheduledReport
	1,  // 6: hulation.v1.reports.UpdateReportRequest.report:type_name -> hulation.v1.reports.ScheduledReport
	1,  // 7: hulation.v1.reports.ListReportsResponse.reports:type_name -> hulation.v1.reports.ScheduledReport
	16, // 8: hulation.v1.reports.PreviewReportRequest.filters:type_name -> hulation.v1.reports.Filters
	15, // 9: hulation.v1.reports.ListRunsResponse.runs:type_name -> hulation.v1.reports.ReportRun
	17, // 10: hulation.v1.reports.ReportRun.started_at:type_name -> google.protobuf.Timestamp
	17, // 11: hulation.v1.reports.ReportRun.finished_at:type_name -> google.protobuf.Timestamp
	2,  // 12: hulation.v1.reports.ReportsService.CreateReport:input_type -> hulation.v1.reports.CreateReportRequest
	3,  // 13: hulation.v1.reports.ReportsService.UpdateReport:input_type -> hulation.v1.reports.UpdateReportRequest
	4,  // 14: hulation.v1.reports.ReportsService.DeleteReport:input_type -> hulation.v1.reports.DeleteReportRequest
	6,  // 15: hulation.v1.reports.ReportsService.ListReports:input_type -> hulation.v1.reports.ListReportsRequest
	8,  // 16: hulation.v1.reports.ReportsService.GetReport:input_type -> hulation.v1.reports.GetReportRequest
	9,  // 17: hulation.v1.reports.ReportsService.PreviewReport:input_type -> hulation.v1.reports.PreviewReportRequest
	11, // 18: hulation.v1.reports.ReportsService.SendNow:input_type -> hulation.v1.reports.SendNowRequest
	13, // 19: hulation.v1.reports.ReportsService.ListRuns:input_type -> hulation.v1.reports.ListRunsRequest
	1,  // 20: hulation.v1.reports.ReportsService.CreateReport:output_type -> hulation.v1.reports.ScheduledReport
	1,  // 21: hulation.v1.reports.ReportsService.UpdateReport:output_type -> hulation.v1.reports.ScheduledReport
	5,  // 22: hulation.v1.reports.ReportsService.DeleteReport:output_type -> hulation.v1.reports.DeleteReportResponse
	7,  // 23: hulation.v1.reports.ReportsService.ListReports:output_type -> hulation.v1.reports.ListReportsResponse
	1,  // 24: hulation.v1.reports.ReportsService.GetReport:output_type -> hulation.v1.reports.ScheduledReport
	10, // 25: hulation.v1.reports.ReportsService.PreviewReport:output_type -> hulation.v1.reports.PreviewReportResponse
	12, // 26: hulation.v1.reports.ReportsService.SendNow:output_type -> hulation.v1.reports.SendNowResponse
	14, // 27: hulation.v1.reports.ReportsService.ListRuns:output_type -> hulation.v1.reports.ListRunsResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_apispec_v1_reports_reports_proto_init() }
func file_pkg_apispec_v1_reports_reports_proto_init() {
	if File_pkg_apispec_v1_reports_reports_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_reports_reports_proto_rawDesc), len(file_pkg_apispec_v1_reports_reports_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apispec_v1_reports_reports_proto_goTypes,
		DependencyIndexes: file_pkg_apispec_v1_reports_reports_proto_depIdxs,
		EnumInfos:         file_pkg_apispec_v1_reports_reports_proto_enumTypes,
		MessageInfos:      file_pkg_apispec_v1_reports_reports_proto_msgTypes,
	}.Build()
	File_pkg_apispec_v1_reports_reports_proto = out.File
	file_pkg_apispec_v1_reports_reports_proto_goTypes = nil
	file_pkg_apispec_v1_reports_reports_proto_depIdxs = nil
}
