// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/apispec/v1/analytics/analytics.proto

// AnalyticsService — Phase-0 SKELETON ONLY.
//
// Message types and RPC shapes are defined here so the Svelte UI can begin
// design work against a stable contract, and so downstream code generation
// keeps working. Implementations are empty stubs in Phase 0; Phase 1 fills
// them in.

package analyticsspec

import (
	_ "github.com/tlalocweb/hulation/protoext/izuma/auth"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common filter parameters used across report queries. Every analytics RPC
// takes these via query string (the grpc-gateway maps fields 1:1).
type Filters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_ids — intersected with user's allowed set by the backend.
	ServerIds []string `protobuf:"bytes,1,rep,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"`
	// from / to — ISO-8601 timestamps (e.g. "2026-04-14T00:00Z").
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// granularity: "hour" | "day" | "week"
	Granularity string `protobuf:"bytes,4,opt,name=granularity,proto3" json:"granularity,omitempty"`
	// compare: "previous" | "previous_year" | ""
	Compare string `protobuf:"bytes,5,opt,name=compare,proto3" json:"compare,omitempty"`
	// drill-down chip filters
	Country   string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Device    string `protobuf:"bytes,7,opt,name=device,proto3" json:"device,omitempty"` // "mobile" | "tablet" | "desktop"
	Source    string `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"` // referer host or channel name
	Path      string `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	EventCode string `protobuf:"bytes,10,opt,name=event_code,json=eventCode,proto3" json:"event_code,omitempty"`
	Goal      string `protobuf:"bytes,11,opt,name=goal,proto3" json:"goal,omitempty"`
	// Additional drill-down chips (wired 1:1 to ClickHouse columns).
	Browser       string `protobuf:"bytes,12,opt,name=browser,proto3" json:"browser,omitempty"`
	Os            string `protobuf:"bytes,13,opt,name=os,proto3" json:"os,omitempty"`
	Channel       string `protobuf:"bytes,14,opt,name=channel,proto3" json:"channel,omitempty"` // "direct" | "search" | "social" | "referral" | "email"
	UtmSource     string `protobuf:"bytes,15,opt,name=utm_source,json=utmSource,proto3" json:"utm_source,omitempty"`
	UtmMedium     string `protobuf:"bytes,16,opt,name=utm_medium,json=utmMedium,proto3" json:"utm_medium,omitempty"`
	UtmCampaign   string `protobuf:"bytes,17,opt,name=utm_campaign,json=utmCampaign,proto3" json:"utm_campaign,omitempty"`
	Region        string `protobuf:"bytes,18,opt,name=region,proto3" json:"region,omitempty"` // geography sub-drill (admin region)
	City          string `protobuf:"bytes,19,opt,name=city,proto3" json:"city,omitempty"`     // geography sub-drill (city)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *Filters) GetServerIds() []string {
	if x != nil {
		return x.ServerIds
	}
	return nil
}

func (x *Filters) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Filters) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Filters) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *Filters) GetCompare() string {
	if x != nil {
		return x.Compare
	}
	return ""
}

func (x *Filters) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Filters) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Filters) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Filters) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Filters) GetEventCode() string {
	if x != nil {
		return x.EventCode
	}
	return ""
}

func (x *Filters) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Filters) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Filters) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Filters) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Filters) GetUtmSource() string {
	if x != nil {
		return x.UtmSource
	}
	return ""
}

func (x *Filters) GetUtmMedium() string {
	if x != nil {
		return x.UtmMedium
	}
	return ""
}

func (x *Filters) GetUtmCampaign() string {
	if x != nil {
		return x.UtmCampaign
	}
	return ""
}

func (x *Filters) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Filters) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SummaryRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type SummaryResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Visitors                  int64                  `protobuf:"varint,1,opt,name=visitors,proto3" json:"visitors,omitempty"`
	Pageviews                 int64                  `protobuf:"varint,2,opt,name=pageviews,proto3" json:"pageviews,omitempty"`
	BounceRate                float64                `protobuf:"fixed64,3,opt,name=bounce_rate,json=bounceRate,proto3" json:"bounce_rate,omitempty"`
	AvgSessionDurationSeconds float64                `protobuf:"fixed64,4,opt,name=avg_session_duration_seconds,json=avgSessionDurationSeconds,proto3" json:"avg_session_duration_seconds,omitempty"`
	// deltas vs. comparison period (percent, -1 if no comparison requested).
	VisitorsDeltaPct           float64   `protobuf:"fixed64,5,opt,name=visitors_delta_pct,json=visitorsDeltaPct,proto3" json:"visitors_delta_pct,omitempty"`
	PageviewsDeltaPct          float64   `protobuf:"fixed64,6,opt,name=pageviews_delta_pct,json=pageviewsDeltaPct,proto3" json:"pageviews_delta_pct,omitempty"`
	BounceRateDeltaPct         float64   `protobuf:"fixed64,7,opt,name=bounce_rate_delta_pct,json=bounceRateDeltaPct,proto3" json:"bounce_rate_delta_pct,omitempty"`
	AvgSessionDurationDeltaPct float64   `protobuf:"fixed64,8,opt,name=avg_session_duration_delta_pct,json=avgSessionDurationDeltaPct,proto3" json:"avg_session_duration_delta_pct,omitempty"`
	Sparkline                  []float64 `protobuf:"fixed64,9,rep,packed,name=sparkline,proto3" json:"sparkline,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *SummaryResponse) GetVisitors() int64 {
	if x != nil {
		return x.Visitors
	}
	return 0
}

func (x *SummaryResponse) GetPageviews() int64 {
	if x != nil {
		return x.Pageviews
	}
	return 0
}

func (x *SummaryResponse) GetBounceRate() float64 {
	if x != nil {
		return x.BounceRate
	}
	return 0
}

func (x *SummaryResponse) GetAvgSessionDurationSeconds() float64 {
	if x != nil {
		return x.AvgSessionDurationSeconds
	}
	return 0
}

func (x *SummaryResponse) GetVisitorsDeltaPct() float64 {
	if x != nil {
		return x.VisitorsDeltaPct
	}
	return 0
}

func (x *SummaryResponse) GetPageviewsDeltaPct() float64 {
	if x != nil {
		return x.PageviewsDeltaPct
	}
	return 0
}

func (x *SummaryResponse) GetBounceRateDeltaPct() float64 {
	if x != nil {
		return x.BounceRateDeltaPct
	}
	return 0
}

func (x *SummaryResponse) GetAvgSessionDurationDeltaPct() float64 {
	if x != nil {
		return x.AvgSessionDurationDeltaPct
	}
	return 0
}

func (x *SummaryResponse) GetSparkline() []float64 {
	if x != nil {
		return x.Sparkline
	}
	return nil
}

type TimeseriesBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            string                 `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Visitors      int64                  `protobuf:"varint,2,opt,name=visitors,proto3" json:"visitors,omitempty"`
	Pageviews     int64                  `protobuf:"varint,3,opt,name=pageviews,proto3" json:"pageviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeseriesBucket) Reset() {
	*x = TimeseriesBucket{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeseriesBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeseriesBucket) ProtoMessage() {}

func (x *TimeseriesBucket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeseriesBucket.ProtoReflect.Descriptor instead.
func (*TimeseriesBucket) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *TimeseriesBucket) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *TimeseriesBucket) GetVisitors() int64 {
	if x != nil {
		return x.Visitors
	}
	return 0
}

func (x *TimeseriesBucket) GetPageviews() int64 {
	if x != nil {
		return x.Pageviews
	}
	return 0
}

type TimeseriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeseriesRequest) Reset() {
	*x = TimeseriesRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeseriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeseriesRequest) ProtoMessage() {}

func (x *TimeseriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeseriesRequest.ProtoReflect.Descriptor instead.
func (*TimeseriesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TimeseriesRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *TimeseriesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type TimeseriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*TimeseriesBucket    `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeseriesResponse) Reset() {
	*x = TimeseriesResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeseriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeseriesResponse) ProtoMessage() {}

func (x *TimeseriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeseriesResponse.ProtoReflect.Descriptor instead.
func (*TimeseriesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *TimeseriesResponse) GetBuckets() []*TimeseriesBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

// TableRow is the shared row shape across Pages, Sources, Geography,
// Events, and FormsReport. Each report populates only the fields that
// apply to its dimension; unset numeric fields serialise to zero, which
// the UI tolerates.
type TableRow struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Key        string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Visitors   int64                  `protobuf:"varint,2,opt,name=visitors,proto3" json:"visitors,omitempty"`
	Pageviews  int64                  `protobuf:"varint,3,opt,name=pageviews,proto3" json:"pageviews,omitempty"`
	BounceRate float64                `protobuf:"fixed64,4,opt,name=bounce_rate,json=bounceRate,proto3" json:"bounce_rate,omitempty"`
	// Pages report.
	UniquePageviews      int64   `protobuf:"varint,5,opt,name=unique_pageviews,json=uniquePageviews,proto3" json:"unique_pageviews,omitempty"`
	AvgTimeOnPageSeconds float64 `protobuf:"fixed64,6,opt,name=avg_time_on_page_seconds,json=avgTimeOnPageSeconds,proto3" json:"avg_time_on_page_seconds,omitempty"`
	Entrances            int64   `protobuf:"varint,7,opt,name=entrances,proto3" json:"entrances,omitempty"`
	Exits                int64   `protobuf:"varint,8,opt,name=exits,proto3" json:"exits,omitempty"`
	// Sources report.
	PagesPerVisit float64 `protobuf:"fixed64,9,opt,name=pages_per_visit,json=pagesPerVisit,proto3" json:"pages_per_visit,omitempty"`
	GoalConvRate  float64 `protobuf:"fixed64,10,opt,name=goal_conv_rate,json=goalConvRate,proto3" json:"goal_conv_rate,omitempty"`
	// Geography report.
	Percent float64 `protobuf:"fixed64,11,opt,name=percent,proto3" json:"percent,omitempty"`
	// Events report.
	Count          int64  `protobuf:"varint,12,opt,name=count,proto3" json:"count,omitempty"`
	UniqueVisitors int64  `protobuf:"varint,13,opt,name=unique_visitors,json=uniqueVisitors,proto3" json:"unique_visitors,omitempty"`
	FirstSeen      string `protobuf:"bytes,14,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen       string `protobuf:"bytes,15,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// FormsReport report.
	Submits                int64   `protobuf:"varint,16,opt,name=submits,proto3" json:"submits,omitempty"`
	ConversionRate         float64 `protobuf:"fixed64,17,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	AvgTimeToSubmitSeconds float64 `protobuf:"fixed64,18,opt,name=avg_time_to_submit_seconds,json=avgTimeToSubmitSeconds,proto3" json:"avg_time_to_submit_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TableRow) Reset() {
	*x = TableRow{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRow) ProtoMessage() {}

func (x *TableRow) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRow.ProtoReflect.Descriptor instead.
func (*TableRow) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *TableRow) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TableRow) GetVisitors() int64 {
	if x != nil {
		return x.Visitors
	}
	return 0
}

func (x *TableRow) GetPageviews() int64 {
	if x != nil {
		return x.Pageviews
	}
	return 0
}

func (x *TableRow) GetBounceRate() float64 {
	if x != nil {
		return x.BounceRate
	}
	return 0
}

func (x *TableRow) GetUniquePageviews() int64 {
	if x != nil {
		return x.UniquePageviews
	}
	return 0
}

func (x *TableRow) GetAvgTimeOnPageSeconds() float64 {
	if x != nil {
		return x.AvgTimeOnPageSeconds
	}
	return 0
}

func (x *TableRow) GetEntrances() int64 {
	if x != nil {
		return x.Entrances
	}
	return 0
}

func (x *TableRow) GetExits() int64 {
	if x != nil {
		return x.Exits
	}
	return 0
}

func (x *TableRow) GetPagesPerVisit() float64 {
	if x != nil {
		return x.PagesPerVisit
	}
	return 0
}

func (x *TableRow) GetGoalConvRate() float64 {
	if x != nil {
		return x.GoalConvRate
	}
	return 0
}

func (x *TableRow) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *TableRow) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TableRow) GetUniqueVisitors() int64 {
	if x != nil {
		return x.UniqueVisitors
	}
	return 0
}

func (x *TableRow) GetFirstSeen() string {
	if x != nil {
		return x.FirstSeen
	}
	return ""
}

func (x *TableRow) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *TableRow) GetSubmits() int64 {
	if x != nil {
		return x.Submits
	}
	return 0
}

func (x *TableRow) GetConversionRate() float64 {
	if x != nil {
		return x.ConversionRate
	}
	return 0
}

func (x *TableRow) GetAvgTimeToSubmitSeconds() float64 {
	if x != nil {
		return x.AvgTimeToSubmitSeconds
	}
	return 0
}

type PagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesRequest) Reset() {
	*x = PagesRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesRequest) ProtoMessage() {}

func (x *PagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesRequest.ProtoReflect.Descriptor instead.
func (*PagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *PagesRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *PagesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *PagesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TableRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesResponse) Reset() {
	*x = PagesResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesResponse) ProtoMessage() {}

func (x *PagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesResponse.ProtoReflect.Descriptor instead.
func (*PagesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *PagesResponse) GetRows() []*TableRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type SourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	GroupBy       string                 `protobuf:"bytes,4,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcesRequest) Reset() {
	*x = SourcesRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcesRequest) ProtoMessage() {}

func (x *SourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcesRequest.ProtoReflect.Descriptor instead.
func (*SourcesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *SourcesRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SourcesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SourcesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SourcesRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *SourcesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SourcesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TableRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcesResponse) Reset() {
	*x = SourcesResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcesResponse) ProtoMessage() {}

func (x *SourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcesResponse.ProtoReflect.Descriptor instead.
func (*SourcesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *SourcesResponse) GetRows() []*TableRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GeographyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeographyRequest) Reset() {
	*x = GeographyRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeographyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeographyRequest) ProtoMessage() {}

func (x *GeographyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeographyRequest.ProtoReflect.Descriptor instead.
func (*GeographyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GeographyRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GeographyRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GeographyRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GeographyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TableRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeographyResponse) Reset() {
	*x = GeographyResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeographyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeographyResponse) ProtoMessage() {}

func (x *GeographyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeographyResponse.ProtoReflect.Descriptor instead.
func (*GeographyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *GeographyResponse) GetRows() []*TableRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type DevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicesRequest) Reset() {
	*x = DevicesRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesRequest) ProtoMessage() {}

func (x *DevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesRequest.ProtoReflect.Descriptor instead.
func (*DevicesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *DevicesRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *DevicesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DevicesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type DevicesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceCategory []*TableRow            `protobuf:"bytes,1,rep,name=device_category,json=deviceCategory,proto3" json:"device_category,omitempty"`
	Browser        []*TableRow            `protobuf:"bytes,2,rep,name=browser,proto3" json:"browser,omitempty"`
	Os             []*TableRow            `protobuf:"bytes,3,rep,name=os,proto3" json:"os,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DevicesResponse) Reset() {
	*x = DevicesResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesResponse) ProtoMessage() {}

func (x *DevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesResponse.ProtoReflect.Descriptor instead.
func (*DevicesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *DevicesResponse) GetDeviceCategory() []*TableRow {
	if x != nil {
		return x.DeviceCategory
	}
	return nil
}

func (x *DevicesResponse) GetBrowser() []*TableRow {
	if x != nil {
		return x.Browser
	}
	return nil
}

func (x *DevicesResponse) GetOs() []*TableRow {
	if x != nil {
		return x.Os
	}
	return nil
}

type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *EventsRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *EventsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *EventsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TableRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *EventsResponse) GetRows() []*TableRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type FormsReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormsReportRequest) Reset() {
	*x = FormsReportRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormsReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormsReportRequest) ProtoMessage() {}

func (x *FormsReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormsReportRequest.ProtoReflect.Descriptor instead.
func (*FormsReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *FormsReportRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *FormsReportRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *FormsReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type FormsReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TableRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormsReportResponse) Reset() {
	*x = FormsReportResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormsReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormsReportResponse) ProtoMessage() {}

func (x *FormsReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormsReportResponse.ProtoReflect.Descriptor instead.
func (*FormsReportResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *FormsReportResponse) GetRows() []*TableRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type VisitorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *Filters               `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorsRequest) Reset() {
	*x = VisitorsRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorsRequest) ProtoMessage() {}

func (x *VisitorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorsRequest.ProtoReflect.Descriptor instead.
func (*VisitorsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{19}
}

func (x *VisitorsRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *VisitorsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *VisitorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *VisitorsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *VisitorsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type VisitorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visitors      []*VisitorSummary      `protobuf:"bytes,1,rep,name=visitors,proto3" json:"visitors,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorsResponse) Reset() {
	*x = VisitorsResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorsResponse) ProtoMessage() {}

func (x *VisitorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorsResponse.ProtoReflect.Descriptor instead.
func (*VisitorsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{20}
}

func (x *VisitorsResponse) GetVisitors() []*VisitorSummary {
	if x != nil {
		return x.Visitors
	}
	return nil
}

func (x *VisitorsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VisitorSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitorId     string                 `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstSeen     string                 `protobuf:"bytes,3,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      string                 `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Sessions      int32                  `protobuf:"varint,5,opt,name=sessions,proto3" json:"sessions,omitempty"`
	Pageviews     int32                  `protobuf:"varint,6,opt,name=pageviews,proto3" json:"pageviews,omitempty"`
	Events        int32                  `protobuf:"varint,7,opt,name=events,proto3" json:"events,omitempty"`
	TopCountry    string                 `protobuf:"bytes,8,opt,name=top_country,json=topCountry,proto3" json:"top_country,omitempty"`
	TopDevice     string                 `protobuf:"bytes,9,opt,name=top_device,json=topDevice,proto3" json:"top_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorSummary) Reset() {
	*x = VisitorSummary{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorSummary) ProtoMessage() {}

func (x *VisitorSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorSummary.ProtoReflect.Descriptor instead.
func (*VisitorSummary) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{21}
}

func (x *VisitorSummary) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *VisitorSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VisitorSummary) GetFirstSeen() string {
	if x != nil {
		return x.FirstSeen
	}
	return ""
}

func (x *VisitorSummary) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *VisitorSummary) GetSessions() int32 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

func (x *VisitorSummary) GetPageviews() int32 {
	if x != nil {
		return x.Pageviews
	}
	return 0
}

func (x *VisitorSummary) GetEvents() int32 {
	if x != nil {
		return x.Events
	}
	return 0
}

func (x *VisitorSummary) GetTopCountry() string {
	if x != nil {
		return x.TopCountry
	}
	return ""
}

func (x *VisitorSummary) GetTopDevice() string {
	if x != nil {
		return x.TopDevice
	}
	return ""
}

type VisitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	VisitorId     string                 `protobuf:"bytes,2,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorRequest) Reset() {
	*x = VisitorRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorRequest) ProtoMessage() {}

func (x *VisitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorRequest.ProtoReflect.Descriptor instead.
func (*VisitorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{22}
}

func (x *VisitorRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *VisitorRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

type VisitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visitor       *VisitorSummary        `protobuf:"bytes,1,opt,name=visitor,proto3" json:"visitor,omitempty"`
	Timeline      []*VisitorEvent        `protobuf:"bytes,2,rep,name=timeline,proto3" json:"timeline,omitempty"`
	Ips           []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	Cookies       []string               `protobuf:"bytes,4,rep,name=cookies,proto3" json:"cookies,omitempty"`
	Aliases       []string               `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorResponse) Reset() {
	*x = VisitorResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorResponse) ProtoMessage() {}

func (x *VisitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorResponse.ProtoReflect.Descriptor instead.
func (*VisitorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{23}
}

func (x *VisitorResponse) GetVisitor() *VisitorSummary {
	if x != nil {
		return x.Visitor
	}
	return nil
}

func (x *VisitorResponse) GetTimeline() []*VisitorEvent {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *VisitorResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *VisitorResponse) GetCookies() []string {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *VisitorResponse) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type VisitorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            string                 `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	EventCode     string                 `protobuf:"bytes,2,opt,name=event_code,json=eventCode,proto3" json:"event_code,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Referrer      string                 `protobuf:"bytes,4,opt,name=referrer,proto3" json:"referrer,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Device        string                 `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorEvent) Reset() {
	*x = VisitorEvent{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorEvent) ProtoMessage() {}

func (x *VisitorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorEvent.ProtoReflect.Descriptor instead.
func (*VisitorEvent) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{24}
}

func (x *VisitorEvent) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *VisitorEvent) GetEventCode() string {
	if x != nil {
		return x.EventCode
	}
	return ""
}

func (x *VisitorEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VisitorEvent) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *VisitorEvent) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *VisitorEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *VisitorEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RealtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeRequest) Reset() {
	*x = RealtimeRequest{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeRequest) ProtoMessage() {}

func (x *RealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeRequest.ProtoReflect.Descriptor instead.
func (*RealtimeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{25}
}

func (x *RealtimeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type RealtimeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveVisitors_5M int32                  `protobuf:"varint,1,opt,name=active_visitors_5m,json=activeVisitors5m,proto3" json:"active_visitors_5m,omitempty"`
	Recent            []*VisitorEvent        `protobuf:"bytes,2,rep,name=recent,proto3" json:"recent,omitempty"`
	TopPages          []*TableRow            `protobuf:"bytes,3,rep,name=top_pages,json=topPages,proto3" json:"top_pages,omitempty"`
	TopSources        []*TableRow            `protobuf:"bytes,4,rep,name=top_sources,json=topSources,proto3" json:"top_sources,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RealtimeResponse) Reset() {
	*x = RealtimeResponse{}
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeResponse) ProtoMessage() {}

func (x *RealtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_analytics_analytics_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeResponse.ProtoReflect.Descriptor instead.
func (*RealtimeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP(), []int{26}
}

func (x *RealtimeResponse) GetActiveVisitors_5M() int32 {
	if x != nil {
		return x.ActiveVisitors_5M
	}
	return 0
}

func (x *RealtimeResponse) GetRecent() []*VisitorEvent {
	if x != nil {
		return x.Recent
	}
	return nil
}

func (x *RealtimeResponse) GetTopPages() []*TableRow {
	if x != nil {
		return x.TopPages
	}
	return nil
}

func (x *RealtimeResponse) GetTopSources() []*TableRow {
	if x != nil {
		return x.TopSources
	}
	return nil
}

var File_pkg_apispec_v1_analytics_analytics_proto protoreflect.FileDescriptor

const file_pkg_apispec_v1_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"(pkg/apispec/v1/analytics/analytics.proto\x12\x15hulation.v1.analytics\x1a\x1cgoogle/api/annotations.proto\x1a\x1bizuma/auth/permission.proto\"\xea\x03\n" +
	"\aFilters\x12\x1d\n" +
	"\n" +
	"server_ids\x18\x01 \x03(\tR\tserverIds\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12 \n" +
	"\vgranularity\x18\x04 \x01(\tR\vgranularity\x12\x18\n" +
	"\acompare\x18\x05 \x01(\tR\acompare\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x16\n" +
	"\x06device\x18\a \x01(\tR\x06device\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"event_code\x18\n" +
	" \x01(\tR\teventCode\x12\x12\n" +
	"\x04goal\x18\v \x01(\tR\x04goal\x12\x18\n" +
	"\abrowser\x18\f \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\r \x01(\tR\x02os\x12\x18\n" +
	"\achannel\x18\x0e \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"utm_source\x18\x0f \x01(\tR\tutmSource\x12\x1d\n" +
	"\n" +
	"utm_medium\x18\x10 \x01(\tR\tutmMedium\x12!\n" +
	"\futm_campaign\x18\x11 \x01(\tR\vutmCampaign\x12\x16\n" +
	"\x06region\x18\x12 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x13 \x01(\tR\x04city\"g\n" +
	"\x0eSummaryRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"\xa0\x03\n" +
	"\x0fSummaryResponse\x12\x1a\n" +
	"\bvisitors\x18\x01 \x01(\x03R\bvisitors\x12\x1c\n" +
	"\tpageviews\x18\x02 \x01(\x03R\tpageviews\x12\x1f\n" +
	"\vbounce_rate\x18\x03 \x01(\x01R\n" +
	"bounceRate\x12?\n" +
	"\x1cavg_session_duration_seconds\x18\x04 \x01(\x01R\x19avgSessionDurationSeconds\x12,\n" +
	"\x12visitors_delta_pct\x18\x05 \x01(\x01R\x10visitorsDeltaPct\x12.\n" +
	"\x13pageviews_delta_pct\x18\x06 \x01(\x01R\x11pageviewsDeltaPct\x121\n" +
	"\x15bounce_rate_delta_pct\x18\a \x01(\x01R\x12bounceRateDeltaPct\x12B\n" +
	"\x1eavg_session_duration_delta_pct\x18\b \x01(\x01R\x1aavgSessionDurationDeltaPct\x12\x1c\n" +
	"\tsparkline\x18\t \x03(\x01R\tsparkline\"\\\n" +
	"\x10TimeseriesBucket\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\tR\x02ts\x12\x1a\n" +
	"\bvisitors\x18\x02 \x01(\x03R\bvisitors\x12\x1c\n" +
	"\tpageviews\x18\x03 \x01(\x03R\tpageviews\"j\n" +
	"\x11TimeseriesRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"W\n" +
	"\x12TimeseriesResponse\x12A\n" +
	"\abuckets\x18\x01 \x03(\v2'.hulation.v1.analytics.TimeseriesBucketR\abuckets\"\xf0\x04\n" +
	"\bTableRow\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bvisitors\x18\x02 \x01(\x03R\bvisitors\x12\x1c\n" +
	"\tpageviews\x18\x03 \x01(\x03R\tpageviews\x12\x1f\n" +
	"\vbounce_rate\x18\x04 \x01(\x01R\n" +
	"bounceRate\x12)\n" +
	"\x10unique_pageviews\x18\x05 \x01(\x03R\x0funiquePageviews\x126\n" +
	"\x18avg_time_on_page_seconds\x18\x06 \x01(\x01R\x14avgTimeOnPageSeconds\x12\x1c\n" +
	"\tentrances\x18\a \x01(\x03R\tentrances\x12\x14\n" +
	"\x05exits\x18\b \x01(\x03R\x05exits\x12&\n" +
	"\x0fpages_per_visit\x18\t \x01(\x01R\rpagesPerVisit\x12$\n" +
	"\x0egoal_conv_rate\x18\n" +
	" \x01(\x01R\fgoalConvRate\x12\x18\n" +
	"\apercent\x18\v \x01(\x01R\apercent\x12\x14\n" +
	"\x05count\x18\f \x01(\x03R\x05count\x12'\n" +
	"\x0funique_visitors\x18\r \x01(\x03R\x0euniqueVisitors\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x0e \x01(\tR\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\x0f \x01(\tR\blastSeen\x12\x18\n" +
	"\asubmits\x18\x10 \x01(\x03R\asubmits\x12'\n" +
	"\x0fconversion_rate\x18\x11 \x01(\x01R\x0econversionRate\x12:\n" +
	"\x1aavg_time_to_submit_seconds\x18\x12 \x01(\x01R\x16avgTimeToSubmitSeconds\"\xab\x01\n" +
	"\fPagesRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"D\n" +
	"\rPagesResponse\x123\n" +
	"\x04rows\x18\x01 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\x04rows\"\xc8\x01\n" +
	"\x0eSourcesRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x19\n" +
	"\bgroup_by\x18\x04 \x01(\tR\agroupBy\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"F\n" +
	"\x0fSourcesResponse\x123\n" +
	"\x04rows\x18\x01 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\x04rows\"\x81\x01\n" +
	"\x10GeographyRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"H\n" +
	"\x11GeographyResponse\x123\n" +
	"\x04rows\x18\x01 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\x04rows\"\x7f\n" +
	"\x0eDevicesRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"\xc7\x01\n" +
	"\x0fDevicesResponse\x12H\n" +
	"\x0fdevice_category\x18\x01 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\x0edeviceCategory\x129\n" +
	"\abrowser\x18\x02 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\abrowser\x12/\n" +
	"\x02os\x18\x03 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\x02os\"~\n" +
	"\rEventsRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"E\n" +
	"\x0eEventsResponse\x123\n" +
	"\x04rows\x18\x01 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\x04rows\"\x83\x01\n" +
	"\x12FormsReportRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"J\n" +
	"\x13FormsReportResponse\x123\n" +
	"\x04rows\x18\x01 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\x04rows\"\xae\x01\n" +
	"\x0fVisitorsRequest\x128\n" +
	"\afilters\x18\x01 \x01(\v2\x1e.hulation.v1.analytics.FiltersR\afilters\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"k\n" +
	"\x10VisitorsResponse\x12A\n" +
	"\bvisitors\x18\x01 \x03(\v2%.hulation.v1.analytics.VisitorSummaryR\bvisitors\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x93\x02\n" +
	"\x0eVisitorSummary\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x01 \x01(\tR\tvisitorId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x03 \x01(\tR\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\tR\blastSeen\x12\x1a\n" +
	"\bsessions\x18\x05 \x01(\x05R\bsessions\x12\x1c\n" +
	"\tpageviews\x18\x06 \x01(\x05R\tpageviews\x12\x16\n" +
	"\x06events\x18\a \x01(\x05R\x06events\x12\x1f\n" +
	"\vtop_country\x18\b \x01(\tR\n" +
	"topCountry\x12\x1d\n" +
	"\n" +
	"top_device\x18\t \x01(\tR\ttopDevice\"L\n" +
	"\x0eVisitorRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x02 \x01(\tR\tvisitorId\"\xd9\x01\n" +
	"\x0fVisitorResponse\x12?\n" +
	"\avisitor\x18\x01 \x01(\v2%.hulation.v1.analytics.VisitorSummaryR\avisitor\x12?\n" +
	"\btimeline\x18\x02 \x03(\v2#.hulation.v1.analytics.VisitorEventR\btimeline\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\x12\x18\n" +
	"\acookies\x18\x04 \x03(\tR\acookies\x12\x18\n" +
	"\aaliases\x18\x05 \x03(\tR\aaliases\"\xad\x01\n" +
	"\fVisitorEvent\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\tR\x02ts\x12\x1d\n" +
	"\n" +
	"event_code\x18\x02 \x01(\tR\teventCode\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\breferrer\x18\x04 \x01(\tR\breferrer\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\".\n" +
	"\x0fRealtimeRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\xfd\x01\n" +
	"\x10RealtimeResponse\x12,\n" +
	"\x12active_visitors_5m\x18\x01 \x01(\x05R\x10activeVisitors5m\x12;\n" +
	"\x06recent\x18\x02 \x03(\v2#.hulation.v1.analytics.VisitorEventR\x06recent\x12<\n" +
	"\ttop_pages\x18\x03 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\btopPages\x12@\n" +
	"\vtop_sources\x18\x04 \x03(\v2\x1f.hulation.v1.analytics.TableRowR\n" +
	"topSources2\xd0\x0e\n" +
	"\x10AnalyticsService\x12\xa2\x01\n" +
	"\aSummary\x12%.hulation.v1.analytics.SummaryRequest\x1a&.hulation.v1.analytics.SummaryResponse\"Hҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/analytics/summary\x12\xae\x01\n" +
	"\n" +
	"Timeseries\x12(.hulation.v1.analytics.TimeseriesRequest\x1a).hulation.v1.analytics.TimeseriesResponse\"Kҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/analytics/timeseries\x12\x9a\x01\n" +
	"\x05Pages\x12#.hulation.v1.analytics.PagesRequest\x1a$.hulation.v1.analytics.PagesResponse\"Fҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/analytics/pages\x12\xa2\x01\n" +
	"\aSources\x12%.hulation.v1.analytics.SourcesRequest\x1a&.hulation.v1.analytics.SourcesResponse\"Hҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/analytics/sources\x12\xaa\x01\n" +
	"\tGeography\x12'.hulation.v1.analytics.GeographyRequest\x1a(.hulation.v1.analytics.GeographyResponse\"Jҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/analytics/geography\x12\xa2\x01\n" +
	"\aDevices\x12%.hulation.v1.analytics.DevicesRequest\x1a&.hulation.v1.analytics.DevicesResponse\"Hҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/analytics/devices\x12\x9e\x01\n" +
	"\x06Events\x12$.hulation.v1.analytics.EventsRequest\x1a%.hulation.v1.analytics.EventsResponse\"Gҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/analytics/events\x12\xac\x01\n" +
	"\vFormsReport\x12).hulation.v1.analytics.FormsReportRequest\x1a*.hulation.v1.analytics.FormsReportResponse\"Fҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/analytics/forms\x12\xa6\x01\n" +
	"\bVisitors\x12&.hulation.v1.analytics.VisitorsRequest\x1a'.hulation.v1.analytics.VisitorsResponse\"Iҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/analytics/visitors\x12\xaf\x01\n" +
	"\aVisitor\x12%.hulation.v1.analytics.VisitorRequest\x1a&.hulation.v1.analytics.VisitorResponse\"Uҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02(\x12&/api/v1/analytics/visitor/{visitor_id}\x12\xa6\x01\n" +
	"\bRealtime\x12&.hulation.v1.analytics.RealtimeRequest\x1a'.hulation.v1.analytics.RealtimeResponse\"Iҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/analytics/realtimeBFZDgithub.com/tlalocweb/hulation/pkg/apispec/v1/analytics;analyticsspecb\x06proto3"

var (
	file_pkg_apispec_v1_analytics_analytics_proto_rawDescOnce sync.Once
	file_pkg_apispec_v1_analytics_analytics_proto_rawDescData []byte
)

func file_pkg_apispec_v1_analytics_analytics_proto_rawDescGZIP() []byte {
	file_pkg_apispec_v1_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_pkg_apispec_v1_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_analytics_analytics_proto_rawDesc), len(file_pkg_apispec_v1_analytics_analytics_proto_rawDesc)))
	})
	return file_pkg_apispec_v1_analytics_analytics_proto_rawDescData
}

var file_pkg_apispec_v1_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pkg_apispec_v1_analytics_analytics_proto_goTypes = []any{
	(*Filters)(nil),             // 0: hulation.v1.analytics.Filters
	(*SummaryRequest)(nil),      // 1: hulation.v1.analytics.SummaryRequest
	(*SummaryResponse)(nil),     // 2: hulation.v1.analytics.SummaryResponse
	(*TimeseriesBucket)(nil),    // 3: hulation.v1.analytics.TimeseriesBucket
	(*TimeseriesRequest)(nil),   // 4: hulation.v1.analytics.TimeseriesRequest
	(*TimeseriesResponse)(nil),  // 5: hulation.v1.analytics.TimeseriesResponse
	(*TableRow)(nil),            // 6: hulation.v1.analytics.TableRow
	(*PagesRequest)(nil),        // 7: hulation.v1.analytics.PagesRequest
	(*PagesResponse)(nil),       // 8: hulation.v1.analytics.PagesResponse
	(*SourcesRequest)(nil),      // 9: hulation.v1.analytics.SourcesRequest
	(*SourcesResponse)(nil),     // 10: hulation.v1.analytics.SourcesResponse
	(*GeographyRequest)(nil),    // 11: hulation.v1.analytics.GeographyRequest
	(*GeographyResponse)(nil),   // 12: hulation.v1.analytics.GeographyResponse
	(*DevicesRequest)(nil),      // 13: hulation.v1.analytics.DevicesRequest
	(*DevicesResponse)(nil),     // 14: hulation.v1.analytics.DevicesResponse
	(*EventsRequest)(nil),       // 15: hulation.v1.analytics.EventsRequest
	(*EventsResponse)(nil),      // 16: hulation.v1.analytics.EventsResponse
	(*FormsReportRequest)(nil),  // 17: hulation.v1.analytics.FormsReportRequest
	(*FormsReportResponse)(nil), // 18: hulation.v1.analytics.FormsReportResponse
	(*VisitorsRequest)(nil),     // 19: hulation.v1.analytics.VisitorsRequest
	(*VisitorsResponse)(nil),    // 20: hulation.v1.analytics.VisitorsResponse
	(*VisitorSummary)(nil),      // 21: hulation.v1.analytics.VisitorSummary
	(*VisitorRequest)(nil),      // 22: hulation.v1.analytics.VisitorRequest
	(*VisitorResponse)(nil),     // 23: hulation.v1.analytics.VisitorResponse
	(*VisitorEvent)(nil),        // 24: hulation.v1.analytics.VisitorEvent
	(*RealtimeRequest)(nil),     // 25: hulation.v1.analytics.RealtimeRequest
	(*RealtimeResponse)(nil),    // 26: hulation.v1.analytics.RealtimeResponse
}
var file_pkg_apispec_v1_analytics_analytics_proto_depIdxs = []int32{
	0,  // 0: hulation.v1.analytics.SummaryRequest.filters:type_name -> hulation.v1.analytics.Filters
	0,  // 1: hulation.v1.analytics.TimeseriesRequest.filters:type_name -> hulation.v1.analytics.Filters
	3,  // 2: hulation.v1.analytics.TimeseriesResponse.buckets:type_name -> hulation.v1.analytics.TimeseriesBucket
	0,  // 3: hulation.v1.analytics.PagesRequest.filters:type_name -> hulation.v1.analytics.Filters
	6,  // 4: hulation.v1.analytics.PagesResponse.rows:type_name -> hulation.v1.analytics.TableRow
	0,  // 5: hulation.v1.analytics.SourcesRequest.filters:type_name -> hulation.v1.analytics.Filters
	6,  // 6: hulation.v1.analytics.SourcesResponse.rows:type_name -> hulation.v1.analytics.TableRow
	0,  // 7: hulation.v1.analytics.GeographyRequest.filters:type_name -> hulation.v1.analytics.Filters
	6,  // 8: hulation.v1.analytics.GeographyResponse.rows:type_name -> hulation.v1.analytics.TableRow
	0,  // 9: hulation.v1.analytics.DevicesRequest.filters:type_name -> hulation.v1.analytics.Filters
	6,  // 10: hulation.v1.analytics.DevicesResponse.device_category:type_name -> hulation.v1.analytics.TableRow
	6,  // 11: hulation.v1.analytics.DevicesResponse.browser:type_name -> hulation.v1.analytics.TableRow
	6,  // 12: hulation.v1.analytics.DevicesResponse.os:type_name -> hulation.v1.analytics.TableRow
	0,  // 13: hulation.v1.analytics.EventsRequest.filters:type_name -> hulation.v1.analytics.Filters
	6,  // 14: hulation.v1.analytics.EventsResponse.rows:type_name -> hulation.v1.analytics.TableRow
	0,  // 15: hulation.v1.analytics.FormsReportRequest.filters:type_name -> hulation.v1.analytics.Filters
	6,  // 16: hulation.v1.analytics.FormsReportResponse.rows:type_name -> hulation.v1.analytics.TableRow
	0,  // 17: hulation.v1.analytics.VisitorsRequest.filters:type_name -> hulation.v1.analytics.Filters
	21, // 18: hulation.v1.analytics.VisitorsResponse.visitors:type_name -> hulation.v1.analytics.VisitorSummary
	21, // 19: hulation.v1.analytics.VisitorResponse.visitor:type_name -> hulation.v1.analytics.VisitorSummary
	24, // 20: hulation.v1.analytics.VisitorResponse.timeline:type_name -> hulation.v1.analytics.VisitorEvent
	24, // 21: hulation.v1.analytics.RealtimeResponse.recent:type_name -> hulation.v1.analytics.VisitorEvent
	6,  // 22: hulation.v1.analytics.RealtimeResponse.top_pages:type_name -> hulation.v1.analytics.TableRow
	6,  // 23: hulation.v1.analytics.RealtimeResponse.top_sources:type_name -> hulation.v1.analytics.TableRow
	1,  // 24: hulation.v1.analytics.AnalyticsService.Summary:input_type -> hulation.v1.analytics.SummaryRequest
	4,  // 25: hulation.v1.analytics.AnalyticsService.Timeseries:input_type -> hulation.v1.analytics.TimeseriesRequest
	7,  // 26: hulation.v1.analytics.AnalyticsService.Pages:input_type -> hulation.v1.analytics.PagesRequest
	9,  // 27: hulation.v1.analytics.AnalyticsService.Sources:input_type -> hulation.v1.analytics.SourcesRequest
	11, // 28: hulation.v1.analytics.AnalyticsService.Geography:input_type -> hulation.v1.analytics.GeographyRequest
	13, // 29: hulation.v1.analytics.AnalyticsService.Devices:input_type -> hulation.v1.analytics.DevicesRequest
	15, // 30: hulation.v1.analytics.AnalyticsService.Events:input_type -> hulation.v1.analytics.EventsRequest
	17, // 31: hulation.v1.analytics.AnalyticsService.FormsReport:input_type -> hulation.v1.analytics.FormsReportRequest
	19, // 32: hulation.v1.analytics.AnalyticsService.Visitors:input_type -> hulation.v1.analytics.VisitorsRequest
	22, // 33: hulation.v1.analytics.AnalyticsService.Visitor:input_type -> hulation.v1.analytics.VisitorRequest
	25, // 34: hulation.v1.analytics.AnalyticsService.Realtime:input_type -> hulation.v1.analytics.RealtimeRequest
	2,  // 35: hulation.v1.analytics.AnalyticsService.Summary:output_type -> hulation.v1.analytics.SummaryResponse
	5,  // 36: hulation.v1.analytics.AnalyticsService.Timeseries:output_type -> hulation.v1.analytics.TimeseriesResponse
	8,  // 37: hulation.v1.analytics.AnalyticsService.Pages:output_type -> hulation.v1.analytics.PagesResponse
	10, // 38: hulation.v1.analytics.AnalyticsService.Sources:output_type -> hulation.v1.analytics.SourcesResponse
	12, // 39: hulation.v1.analytics.AnalyticsService.Geography:output_type -> hulation.v1.analytics.GeographyResponse
	14, // 40: hulation.v1.analytics.AnalyticsService.Devices:output_type -> hulation.v1.analytics.DevicesResponse
	16, // 41: hulation.v1.analytics.AnalyticsService.Events:output_type -> hulation.v1.analytics.EventsResponse
	18, // 42: hulation.v1.analytics.AnalyticsService.FormsReport:output_type -> hulation.v1.analytics.FormsReportResponse
	20, // 43: hulation.v1.analytics.AnalyticsService.Visitors:output_type -> hulation.v1.analytics.VisitorsResponse
	23, // 44: hulation.v1.analytics.AnalyticsService.Visitor:output_type -> hulation.v1.analytics.VisitorResponse
	26, // 45: hulation.v1.analytics.AnalyticsService.Realtime:output_type -> hulation.v1.analytics.RealtimeResponse
	35, // [35:46] is the sub-list for method output_type
	24, // [24:35] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pkg_apispec_v1_analytics_analytics_proto_init() }
func file_pkg_apispec_v1_analytics_analytics_proto_init() {
	if File_pkg_apispec_v1_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_analytics_analytics_proto_rawDesc), len(file_pkg_apispec_v1_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apispec_v1_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_pkg_apispec_v1_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_pkg_apispec_v1_analytics_analytics_proto_msgTypes,
	}.Build()
	File_pkg_apispec_v1_analytics_analytics_proto = out.File
	file_pkg_apispec_v1_analytics_analytics_proto_goTypes = nil
	file_pkg_apispec_v1_analytics_analytics_proto_depIdxs = nil
}
