// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/apispec/v1/chat/chat.proto

// ChatService — Phase-4b admin-side chat RPCs.
//
// Visitor-facing chat endpoints (POST /api/v1/chat/start and
// WS /api/v1/chat/ws) live as plain HTTP handlers, not RPCs —
// gRPC doesn't speak WebSocket and the start handler has too many
// non-RPC concerns (Turnstile verification, AfterShip email
// validation, OpenAI moderation, rate limiting). Those are
// modelled in pkg/chat/* + server/chat_*.go.
//
// What lives here is the admin REST surface:
//
//   ListSessions      — All-Chats / Live-Chats table on the SPA.
//   GetSession        — Single-session detail (header chip).
//   GetMessages       — Thread view scroll-back.
//   PostAdminMessage  — Async write (REST fallback for the SPA).
//   CloseSession      — End-of-conversation hook.
//   TakeSession       — Claim a queued session (next-available
//                       routing also calls it implicitly).
//   ReleaseSession    — Give a session back to the queue.
//   GetQueue          — Live-Chats page header: queue depth +
//                       assigned-but-unclaimed list.
//   GetLiveSessions   — Live-Chats body: hub-driven snapshot of
//                       sessions with at least one open WS.
//   SearchMessages    — FTS-backed search across persisted
//                       chat_messages.
//
// Permissions:
//   reads  → server.{server_id}.analytics.read
//   writes → server.{server_id}.admin
// (Same scopes the analytics + alerts RPCs use; no chat-specific
// permission needed for v1.)

package chatspec

import (
	_ "github.com/tlalocweb/hulation/protoext/hula/auth"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatSessionStatus mirrors the LowCardinality(String) column on
// chat_sessions. Keep the enum stable across phases.
type ChatSessionStatus int32

const (
	ChatSessionStatus_CHAT_SESSION_STATUS_UNSPECIFIED ChatSessionStatus = 0
	ChatSessionStatus_CHAT_SESSION_STATUS_QUEUED      ChatSessionStatus = 1 // created, no agent assigned
	ChatSessionStatus_CHAT_SESSION_STATUS_ASSIGNED    ChatSessionStatus = 2 // agent picked, awaiting their per-session WS
	ChatSessionStatus_CHAT_SESSION_STATUS_OPEN        ChatSessionStatus = 3 // live conversation
	ChatSessionStatus_CHAT_SESSION_STATUS_CLOSED      ChatSessionStatus = 4 // explicitly closed
	ChatSessionStatus_CHAT_SESSION_STATUS_EXPIRED     ChatSessionStatus = 5 // stale-cleanup or token expiry
)

// Enum value maps for ChatSessionStatus.
var (
	ChatSessionStatus_name = map[int32]string{
		0: "CHAT_SESSION_STATUS_UNSPECIFIED",
		1: "CHAT_SESSION_STATUS_QUEUED",
		2: "CHAT_SESSION_STATUS_ASSIGNED",
		3: "CHAT_SESSION_STATUS_OPEN",
		4: "CHAT_SESSION_STATUS_CLOSED",
		5: "CHAT_SESSION_STATUS_EXPIRED",
	}
	ChatSessionStatus_value = map[string]int32{
		"CHAT_SESSION_STATUS_UNSPECIFIED": 0,
		"CHAT_SESSION_STATUS_QUEUED":      1,
		"CHAT_SESSION_STATUS_ASSIGNED":    2,
		"CHAT_SESSION_STATUS_OPEN":        3,
		"CHAT_SESSION_STATUS_CLOSED":      4,
		"CHAT_SESSION_STATUS_EXPIRED":     5,
	}
)

func (x ChatSessionStatus) Enum() *ChatSessionStatus {
	p := new(ChatSessionStatus)
	*p = x
	return p
}

func (x ChatSessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatSessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_apispec_v1_chat_chat_proto_enumTypes[0].Descriptor()
}

func (ChatSessionStatus) Type() protoreflect.EnumType {
	return &file_pkg_apispec_v1_chat_chat_proto_enumTypes[0]
}

func (x ChatSessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatSessionStatus.Descriptor instead.
func (ChatSessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{0}
}

// ChatMessageDirection mirrors the LowCardinality(String) column
// on chat_messages.direction.
type ChatMessageDirection int32

const (
	ChatMessageDirection_CHAT_MESSAGE_DIRECTION_UNSPECIFIED ChatMessageDirection = 0
	ChatMessageDirection_CHAT_MESSAGE_DIRECTION_VISITOR     ChatMessageDirection = 1
	ChatMessageDirection_CHAT_MESSAGE_DIRECTION_AGENT       ChatMessageDirection = 2
	ChatMessageDirection_CHAT_MESSAGE_DIRECTION_SYSTEM      ChatMessageDirection = 3
	ChatMessageDirection_CHAT_MESSAGE_DIRECTION_BOT         ChatMessageDirection = 4 // reserved
)

// Enum value maps for ChatMessageDirection.
var (
	ChatMessageDirection_name = map[int32]string{
		0: "CHAT_MESSAGE_DIRECTION_UNSPECIFIED",
		1: "CHAT_MESSAGE_DIRECTION_VISITOR",
		2: "CHAT_MESSAGE_DIRECTION_AGENT",
		3: "CHAT_MESSAGE_DIRECTION_SYSTEM",
		4: "CHAT_MESSAGE_DIRECTION_BOT",
	}
	ChatMessageDirection_value = map[string]int32{
		"CHAT_MESSAGE_DIRECTION_UNSPECIFIED": 0,
		"CHAT_MESSAGE_DIRECTION_VISITOR":     1,
		"CHAT_MESSAGE_DIRECTION_AGENT":       2,
		"CHAT_MESSAGE_DIRECTION_SYSTEM":      3,
		"CHAT_MESSAGE_DIRECTION_BOT":         4,
	}
)

func (x ChatMessageDirection) Enum() *ChatMessageDirection {
	p := new(ChatMessageDirection)
	*p = x
	return p
}

func (x ChatMessageDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessageDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_apispec_v1_chat_chat_proto_enumTypes[1].Descriptor()
}

func (ChatMessageDirection) Type() protoreflect.EnumType {
	return &file_pkg_apispec_v1_chat_chat_proto_enumTypes[1]
}

func (x ChatMessageDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessageDirection.Descriptor instead.
func (ChatMessageDirection) EnumDescriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{1}
}

type ChatSession struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId     string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	VisitorId    string                 `protobuf:"bytes,3,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	VisitorEmail string                 `protobuf:"bytes,4,opt,name=visitor_email,json=visitorEmail,proto3" json:"visitor_email,omitempty"`
	// Denormalised at session-start.
	VisitorCountry  string                 `protobuf:"bytes,5,opt,name=visitor_country,json=visitorCountry,proto3" json:"visitor_country,omitempty"`
	VisitorDevice   string                 `protobuf:"bytes,6,opt,name=visitor_device,json=visitorDevice,proto3" json:"visitor_device,omitempty"`
	VisitorIp       string                 `protobuf:"bytes,7,opt,name=visitor_ip,json=visitorIp,proto3" json:"visitor_ip,omitempty"`
	UserAgent       string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ClosedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	LastMessageAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	MessageCount    uint32                 `protobuf:"varint,13,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	Status          ChatSessionStatus      `protobuf:"varint,14,opt,name=status,proto3,enum=hulation.v1.chat.ChatSessionStatus" json:"status,omitempty"`
	AssignedAgentId string                 `protobuf:"bytes,15,opt,name=assigned_agent_id,json=assignedAgentId,proto3" json:"assigned_agent_id,omitempty"`
	AssignedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	// Free-form JSON the visitor widget attached on /chat/start
	// (page URL, referrer, …). Not parsed server-side.
	Meta          string `protobuf:"bytes,17,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSession) Reset() {
	*x = ChatSession{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSession) ProtoMessage() {}

func (x *ChatSession) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSession.ProtoReflect.Descriptor instead.
func (*ChatSession) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatSession) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ChatSession) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *ChatSession) GetVisitorEmail() string {
	if x != nil {
		return x.VisitorEmail
	}
	return ""
}

func (x *ChatSession) GetVisitorCountry() string {
	if x != nil {
		return x.VisitorCountry
	}
	return ""
}

func (x *ChatSession) GetVisitorDevice() string {
	if x != nil {
		return x.VisitorDevice
	}
	return ""
}

func (x *ChatSession) GetVisitorIp() string {
	if x != nil {
		return x.VisitorIp
	}
	return ""
}

func (x *ChatSession) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ChatSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ChatSession) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *ChatSession) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *ChatSession) GetMessageCount() uint32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ChatSession) GetStatus() ChatSessionStatus {
	if x != nil {
		return x.Status
	}
	return ChatSessionStatus_CHAT_SESSION_STATUS_UNSPECIFIED
}

func (x *ChatSession) GetAssignedAgentId() string {
	if x != nil {
		return x.AssignedAgentId
	}
	return ""
}

func (x *ChatSession) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssignedAt
	}
	return nil
}

func (x *ChatSession) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	VisitorId     string                 `protobuf:"bytes,4,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	Direction     ChatMessageDirection   `protobuf:"varint,5,opt,name=direction,proto3,enum=hulation.v1.chat.ChatMessageDirection" json:"direction,omitempty"`
	SenderId      string                 `protobuf:"bytes,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	When          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ChatMessage) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *ChatMessage) GetDirection() ChatMessageDirection {
	if x != nil {
		return x.Direction
	}
	return ChatMessageDirection_CHAT_MESSAGE_DIRECTION_UNSPECIFIED
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetWhen() *timestamppb.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

type ListSessionsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Filter by status; empty = no filter. Multiple values OR'd.
	Status []ChatSessionStatus    `protobuf:"varint,2,rep,packed,name=status,proto3,enum=hulation.v1.chat.ChatSessionStatus" json:"status,omitempty"`
	From   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// Substring match on visitor_email / visitor_id / assigned_agent_id.
	Q             string `protobuf:"bytes,5,opt,name=q,proto3" json:"q,omitempty"`
	Limit         uint32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32 `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListSessionsRequest) GetStatus() []ChatSessionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListSessionsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListSessionsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListSessionsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sessions []*ChatSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// Total matching the filter pre-paging. The SPA needs this for
	// pagination — ClickHouse doesn't return it implicitly.
	TotalCount    uint64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsResponse) GetSessions() []*ChatSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessagesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PostAdminMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAdminMessageRequest) Reset() {
	*x = PostAdminMessageRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAdminMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAdminMessageRequest) ProtoMessage() {}

func (x *PostAdminMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAdminMessageRequest.ProtoReflect.Descriptor instead.
func (*PostAdminMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *PostAdminMessageRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *PostAdminMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PostAdminMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *CloseSessionRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CloseSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ChatSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *CloseSessionResponse) GetSession() *ChatSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type TakeSessionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServerId  string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// When true an admin-only override claims a session already
	// assigned to a different agent. Surfaces in the SPA as a
	// separate "Force take" affordance (warns first).
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeSessionRequest) Reset() {
	*x = TakeSessionRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeSessionRequest) ProtoMessage() {}

func (x *TakeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeSessionRequest.ProtoReflect.Descriptor instead.
func (*TakeSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{10}
}

func (x *TakeSessionRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *TakeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TakeSessionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ReleaseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionRequest) Reset() {
	*x = ReleaseSessionRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionRequest) ProtoMessage() {}

func (x *ReleaseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseSessionRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ReleaseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueRequest) Reset() {
	*x = GetQueueRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueRequest) ProtoMessage() {}

func (x *GetQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueRequest.ProtoReflect.Descriptor instead.
func (*GetQueueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{12}
}

func (x *GetQueueRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetQueueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sessions waiting for an agent (status=queued).
	Queued []*ChatSession `protobuf:"bytes,1,rep,name=queued,proto3" json:"queued,omitempty"`
	// Sessions assigned but the agent hasn't ack-ed their per-session
	// WS yet (status=assigned).
	Assigned      []*ChatSession `protobuf:"bytes,2,rep,name=assigned,proto3" json:"assigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueResponse) Reset() {
	*x = GetQueueResponse{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueResponse) ProtoMessage() {}

func (x *GetQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueResponse.ProtoReflect.Descriptor instead.
func (*GetQueueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{13}
}

func (x *GetQueueResponse) GetQueued() []*ChatSession {
	if x != nil {
		return x.Queued
	}
	return nil
}

func (x *GetQueueResponse) GetAssigned() []*ChatSession {
	if x != nil {
		return x.Assigned
	}
	return nil
}

type GetLiveSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveSessionsRequest) Reset() {
	*x = GetLiveSessionsRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveSessionsRequest) ProtoMessage() {}

func (x *GetLiveSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetLiveSessionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{14}
}

func (x *GetLiveSessionsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type LiveSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VisitorId     string                 `protobuf:"bytes,2,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	VisitorEmail  string                 `protobuf:"bytes,3,opt,name=visitor_email,json=visitorEmail,proto3" json:"visitor_email,omitempty"`
	VisitorOnline bool                   `protobuf:"varint,4,opt,name=visitor_online,json=visitorOnline,proto3" json:"visitor_online,omitempty"`
	// Agents currently subscribed to the per-session WS.
	Agents        []string               `protobuf:"bytes,5,rep,name=agents,proto3" json:"agents,omitempty"`
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveSession) Reset() {
	*x = LiveSession{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveSession) ProtoMessage() {}

func (x *LiveSession) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveSession.ProtoReflect.Descriptor instead.
func (*LiveSession) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{15}
}

func (x *LiveSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LiveSession) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *LiveSession) GetVisitorEmail() string {
	if x != nil {
		return x.VisitorEmail
	}
	return ""
}

func (x *LiveSession) GetVisitorOnline() bool {
	if x != nil {
		return x.VisitorOnline
	}
	return false
}

func (x *LiveSession) GetAgents() []string {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *LiveSession) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

type GetLiveSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*LiveSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveSessionsResponse) Reset() {
	*x = GetLiveSessionsResponse{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveSessionsResponse) ProtoMessage() {}

func (x *GetLiveSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetLiveSessionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{16}
}

func (x *GetLiveSessionsResponse) GetSessions() []*LiveSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SearchMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Q             string                 `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesRequest) Reset() {
	*x = SearchMessagesRequest{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesRequest) ProtoMessage() {}

func (x *SearchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesRequest.ProtoReflect.Descriptor instead.
func (*SearchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{17}
}

func (x *SearchMessagesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SearchMessagesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchMessagesRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SearchMessagesRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SearchMessagesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchMessagesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesResponse) Reset() {
	*x = SearchMessagesResponse{}
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesResponse) ProtoMessage() {}

func (x *SearchMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_chat_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesResponse.ProtoReflect.Descriptor instead.
func (*SearchMessagesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP(), []int{18}
}

func (x *SearchMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SearchMessagesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_apispec_v1_chat_chat_proto protoreflect.FileDescriptor

const file_pkg_apispec_v1_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/apispec/v1/chat/chat.proto\x12\x10hulation.v1.chat\x1a\x1cgoogle/api/annotations.proto\x1a\x1ahula/auth/permission.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x05\n" +
	"\vChatSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x03 \x01(\tR\tvisitorId\x12#\n" +
	"\rvisitor_email\x18\x04 \x01(\tR\fvisitorEmail\x12'\n" +
	"\x0fvisitor_country\x18\x05 \x01(\tR\x0evisitorCountry\x12%\n" +
	"\x0evisitor_device\x18\x06 \x01(\tR\rvisitorDevice\x12\x1d\n" +
	"\n" +
	"visitor_ip\x18\a \x01(\tR\tvisitorIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgent\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x127\n" +
	"\tclosed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12B\n" +
	"\x0flast_message_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x12#\n" +
	"\rmessage_count\x18\r \x01(\rR\fmessageCount\x12;\n" +
	"\x06status\x18\x0e \x01(\x0e2#.hulation.v1.chat.ChatSessionStatusR\x06status\x12*\n" +
	"\x11assigned_agent_id\x18\x0f \x01(\tR\x0fassignedAgentId\x12;\n" +
	"\vassigned_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\x12\x12\n" +
	"\x04meta\x18\x11 \x01(\tR\x04meta\"\xa5\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x04 \x01(\tR\tvisitorId\x12D\n" +
	"\tdirection\x18\x05 \x01(\x0e2&.hulation.v1.chat.ChatMessageDirectionR\tdirection\x12\x1b\n" +
	"\tsender_id\x18\x06 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12.\n" +
	"\x04when\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04when\"\x87\x02\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12;\n" +
	"\x06status\x18\x02 \x03(\x0e2#.hulation.v1.chat.ChatSessionStatusR\x06status\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\f\n" +
	"\x01q\x18\x05 \x01(\tR\x01q\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\rR\x06offset\"r\n" +
	"\x14ListSessionsResponse\x129\n" +
	"\bsessions\x18\x01 \x03(\v2\x1d.hulation.v1.chat.ChatSessionR\bsessions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"O\n" +
	"\x11GetSessionRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"~\n" +
	"\x12GetMessagesRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"q\n" +
	"\x13GetMessagesResponse\x129\n" +
	"\bmessages\x18\x01 \x03(\v2\x1d.hulation.v1.chat.ChatMessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"o\n" +
	"\x17PostAdminMessageRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"i\n" +
	"\x13CloseSessionRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"O\n" +
	"\x14CloseSessionResponse\x127\n" +
	"\asession\x18\x01 \x01(\v2\x1d.hulation.v1.chat.ChatSessionR\asession\"f\n" +
	"\x12TakeSessionRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"S\n" +
	"\x15ReleaseSessionRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\".\n" +
	"\x0fGetQueueRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\x84\x01\n" +
	"\x10GetQueueResponse\x125\n" +
	"\x06queued\x18\x01 \x03(\v2\x1d.hulation.v1.chat.ChatSessionR\x06queued\x129\n" +
	"\bassigned\x18\x02 \x03(\v2\x1d.hulation.v1.chat.ChatSessionR\bassigned\"5\n" +
	"\x16GetLiveSessionsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\xf3\x01\n" +
	"\vLiveSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x02 \x01(\tR\tvisitorId\x12#\n" +
	"\rvisitor_email\x18\x03 \x01(\tR\fvisitorEmail\x12%\n" +
	"\x0evisitor_online\x18\x04 \x01(\bR\rvisitorOnline\x12\x16\n" +
	"\x06agents\x18\x05 \x03(\tR\x06agents\x12B\n" +
	"\x0flast_message_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\"T\n" +
	"\x17GetLiveSessionsResponse\x129\n" +
	"\bsessions\x18\x01 \x03(\v2\x1d.hulation.v1.chat.LiveSessionR\bsessions\"\xcc\x01\n" +
	"\x15SearchMessagesRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\f\n" +
	"\x01q\x18\x02 \x01(\tR\x01q\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\rR\x06offset\"t\n" +
	"\x16SearchMessagesResponse\x129\n" +
	"\bmessages\x18\x01 \x03(\v2\x1d.hulation.v1.chat.ChatMessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount*\xd9\x01\n" +
	"\x11ChatSessionStatus\x12#\n" +
	"\x1fCHAT_SESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCHAT_SESSION_STATUS_QUEUED\x10\x01\x12 \n" +
	"\x1cCHAT_SESSION_STATUS_ASSIGNED\x10\x02\x12\x1c\n" +
	"\x18CHAT_SESSION_STATUS_OPEN\x10\x03\x12\x1e\n" +
	"\x1aCHAT_SESSION_STATUS_CLOSED\x10\x04\x12\x1f\n" +
	"\x1bCHAT_SESSION_STATUS_EXPIRED\x10\x05*\xc7\x01\n" +
	"\x14ChatMessageDirection\x12&\n" +
	"\"CHAT_MESSAGE_DIRECTION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCHAT_MESSAGE_DIRECTION_VISITOR\x10\x01\x12 \n" +
	"\x1cCHAT_MESSAGE_DIRECTION_AGENT\x10\x02\x12!\n" +
	"\x1dCHAT_MESSAGE_DIRECTION_SYSTEM\x10\x03\x12\x1e\n" +
	"\x1aCHAT_MESSAGE_DIRECTION_BOT\x10\x042\x8b\x0e\n" +
	"\vChatService\x12\xa9\x01\n" +
	"\fListSessions\x12%.hulation.v1.chat.ListSessionsRequest\x1a&.hulation.v1.chat.ListSessionsResponse\"Jҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/chat/admin/sessions\x12\xa9\x01\n" +
	"\n" +
	"GetSession\x12#.hulation.v1.chat.GetSessionRequest\x1a\x1d.hulation.v1.chat.ChatSession\"Wҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02*\x12(/api/v1/chat/admin/sessions/{session_id}\x12\xbc\x01\n" +
	"\vGetMessages\x12$.hulation.v1.chat.GetMessagesRequest\x1a%.hulation.v1.chat.GetMessagesResponse\"`ҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x023\x121/api/v1/chat/admin/sessions/{session_id}/messages\x12\xb8\x01\n" +
	"\x10PostAdminMessage\x12).hulation.v1.chat.PostAdminMessageRequest\x1a\x1d.hulation.v1.chat.ChatMessage\"Zҵ\x18\x1a\n" +
	"\x18server.{server_id}.admin\x82\xd3\xe4\x93\x026:\x01*\"1/api/v1/chat/admin/sessions/{session_id}/messages\x12\xb6\x01\n" +
	"\fCloseSession\x12%.hulation.v1.chat.CloseSessionRequest\x1a&.hulation.v1.chat.CloseSessionResponse\"Wҵ\x18\x1a\n" +
	"\x18server.{server_id}.admin\x82\xd3\xe4\x93\x023:\x01*\"./api/v1/chat/admin/sessions/{session_id}/close\x12\xaa\x01\n" +
	"\vTakeSession\x12$.hulation.v1.chat.TakeSessionRequest\x1a\x1d.hulation.v1.chat.ChatSession\"Vҵ\x18\x1a\n" +
	"\x18server.{server_id}.admin\x82\xd3\xe4\x93\x022:\x01*\"-/api/v1/chat/admin/sessions/{session_id}/take\x12\xb3\x01\n" +
	"\x0eReleaseSession\x12'.hulation.v1.chat.ReleaseSessionRequest\x1a\x1d.hulation.v1.chat.ChatSession\"Yҵ\x18\x1a\n" +
	"\x18server.{server_id}.admin\x82\xd3\xe4\x93\x025:\x01*\"0/api/v1/chat/admin/sessions/{session_id}/release\x12\x9a\x01\n" +
	"\bGetQueue\x12!.hulation.v1.chat.GetQueueRequest\x1a\".hulation.v1.chat.GetQueueResponse\"Gҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/chat/admin/queue\x12\xb7\x01\n" +
	"\x0fGetLiveSessions\x12(.hulation.v1.chat.GetLiveSessionsRequest\x1a).hulation.v1.chat.GetLiveSessionsResponse\"Oҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02\"\x12 /api/v1/chat/admin/live-sessions\x12\xb6\x01\n" +
	"\x0eSearchMessages\x12'.hulation.v1.chat.SearchMessagesRequest\x1a(.hulation.v1.chat.SearchMessagesResponse\"Qҵ\x18#\n" +
	"!server.{server_id}.analytics.read\x82\xd3\xe4\x93\x02$\x12\"/api/v1/chat/admin/messages/searchB<Z:github.com/tlalocweb/hulation/pkg/apispec/v1/chat;chatspecb\x06proto3"

var (
	file_pkg_apispec_v1_chat_chat_proto_rawDescOnce sync.Once
	file_pkg_apispec_v1_chat_chat_proto_rawDescData []byte
)

func file_pkg_apispec_v1_chat_chat_proto_rawDescGZIP() []byte {
	file_pkg_apispec_v1_chat_chat_proto_rawDescOnce.Do(func() {
		file_pkg_apispec_v1_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_chat_chat_proto_rawDesc), len(file_pkg_apispec_v1_chat_chat_proto_rawDesc)))
	})
	return file_pkg_apispec_v1_chat_chat_proto_rawDescData
}

var file_pkg_apispec_v1_chat_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_apispec_v1_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pkg_apispec_v1_chat_chat_proto_goTypes = []any{
	(ChatSessionStatus)(0),          // 0: hulation.v1.chat.ChatSessionStatus
	(ChatMessageDirection)(0),       // 1: hulation.v1.chat.ChatMessageDirection
	(*ChatSession)(nil),             // 2: hulation.v1.chat.ChatSession
	(*ChatMessage)(nil),             // 3: hulation.v1.chat.ChatMessage
	(*ListSessionsRequest)(nil),     // 4: hulation.v1.chat.ListSessionsRequest
	(*ListSessionsResponse)(nil),    // 5: hulation.v1.chat.ListSessionsResponse
	(*GetSessionRequest)(nil),       // 6: hulation.v1.chat.GetSessionRequest
	(*GetMessagesRequest)(nil),      // 7: hulation.v1.chat.GetMessagesRequest
	(*GetMessagesResponse)(nil),     // 8: hulation.v1.chat.GetMessagesResponse
	(*PostAdminMessageRequest)(nil), // 9: hulation.v1.chat.PostAdminMessageRequest
	(*CloseSessionRequest)(nil),     // 10: hulation.v1.chat.CloseSessionRequest
	(*CloseSessionResponse)(nil),    // 11: hulation.v1.chat.CloseSessionResponse
	(*TakeSessionRequest)(nil),      // 12: hulation.v1.chat.TakeSessionRequest
	(*ReleaseSessionRequest)(nil),   // 13: hulation.v1.chat.ReleaseSessionRequest
	(*GetQueueRequest)(nil),         // 14: hulation.v1.chat.GetQueueRequest
	(*GetQueueResponse)(nil),        // 15: hulation.v1.chat.GetQueueResponse
	(*GetLiveSessionsRequest)(nil),  // 16: hulation.v1.chat.GetLiveSessionsRequest
	(*LiveSession)(nil),             // 17: hulation.v1.chat.LiveSession
	(*GetLiveSessionsResponse)(nil), // 18: hulation.v1.chat.GetLiveSessionsResponse
	(*SearchMessagesRequest)(nil),   // 19: hulation.v1.chat.SearchMessagesRequest
	(*SearchMessagesResponse)(nil),  // 20: hulation.v1.chat.SearchMessagesResponse
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
}
var file_pkg_apispec_v1_chat_chat_proto_depIdxs = []int32{
	21, // 0: hulation.v1.chat.ChatSession.started_at:type_name -> google.protobuf.Timestamp
	21, // 1: hulation.v1.chat.ChatSession.closed_at:type_name -> google.protobuf.Timestamp
	21, // 2: hulation.v1.chat.ChatSession.last_message_at:type_name -> google.protobuf.Timestamp
	0,  // 3: hulation.v1.chat.ChatSession.status:type_name -> hulation.v1.chat.ChatSessionStatus
	21, // 4: hulation.v1.chat.ChatSession.assigned_at:type_name -> google.protobuf.Timestamp
	1,  // 5: hulation.v1.chat.ChatMessage.direction:type_name -> hulation.v1.chat.ChatMessageDirection
	21, // 6: hulation.v1.chat.ChatMessage.when:type_name -> google.protobuf.Timestamp
	0,  // 7: hulation.v1.chat.ListSessionsRequest.status:type_name -> hulation.v1.chat.ChatSessionStatus
	21, // 8: hulation.v1.chat.ListSessionsRequest.from:type_name -> google.protobuf.Timestamp
	21, // 9: hulation.v1.chat.ListSessionsRequest.to:type_name -> google.protobuf.Timestamp
	2,  // 10: hulation.v1.chat.ListSessionsResponse.sessions:type_name -> hulation.v1.chat.ChatSession
	3,  // 11: hulation.v1.chat.GetMessagesResponse.messages:type_name -> hulation.v1.chat.ChatMessage
	2,  // 12: hulation.v1.chat.CloseSessionResponse.session:type_name -> hulation.v1.chat.ChatSession
	2,  // 13: hulation.v1.chat.GetQueueResponse.queued:type_name -> hulation.v1.chat.ChatSession
	2,  // 14: hulation.v1.chat.GetQueueResponse.assigned:type_name -> hulation.v1.chat.ChatSession
	21, // 15: hulation.v1.chat.LiveSession.last_message_at:type_name -> google.protobuf.Timestamp
	17, // 16: hulation.v1.chat.GetLiveSessionsResponse.sessions:type_name -> hulation.v1.chat.LiveSession
	21, // 17: hulation.v1.chat.SearchMessagesRequest.from:type_name -> google.protobuf.Timestamp
	21, // 18: hulation.v1.chat.SearchMessagesRequest.to:type_name -> google.protobuf.Timestamp
	3,  // 19: hulation.v1.chat.SearchMessagesResponse.messages:type_name -> hulation.v1.chat.ChatMessage
	4,  // 20: hulation.v1.chat.ChatService.ListSessions:input_type -> hulation.v1.chat.ListSessionsRequest
	6,  // 21: hulation.v1.chat.ChatService.GetSession:input_type -> hulation.v1.chat.GetSessionRequest
	7,  // 22: hulation.v1.chat.ChatService.GetMessages:input_type -> hulation.v1.chat.GetMessagesRequest
	9,  // 23: hulation.v1.chat.ChatService.PostAdminMessage:input_type -> hulation.v1.chat.PostAdminMessageRequest
	10, // 24: hulation.v1.chat.ChatService.CloseSession:input_type -> hulation.v1.chat.CloseSessionRequest
	12, // 25: hulation.v1.chat.ChatService.TakeSession:input_type -> hulation.v1.chat.TakeSessionRequest
	13, // 26: hulation.v1.chat.ChatService.ReleaseSession:input_type -> hulation.v1.chat.ReleaseSessionRequest
	14, // 27: hulation.v1.chat.ChatService.GetQueue:input_type -> hulation.v1.chat.GetQueueRequest
	16, // 28: hulation.v1.chat.ChatService.GetLiveSessions:input_type -> hulation.v1.chat.GetLiveSessionsRequest
	19, // 29: hulation.v1.chat.ChatService.SearchMessages:input_type -> hulation.v1.chat.SearchMessagesRequest
	5,  // 30: hulation.v1.chat.ChatService.ListSessions:output_type -> hulation.v1.chat.ListSessionsResponse
	2,  // 31: hulation.v1.chat.ChatService.GetSession:output_type -> hulation.v1.chat.ChatSession
	8,  // 32: hulation.v1.chat.ChatService.GetMessages:output_type -> hulation.v1.chat.GetMessagesResponse
	3,  // 33: hulation.v1.chat.ChatService.PostAdminMessage:output_type -> hulation.v1.chat.ChatMessage
	11, // 34: hulation.v1.chat.ChatService.CloseSession:output_type -> hulation.v1.chat.CloseSessionResponse
	2,  // 35: hulation.v1.chat.ChatService.TakeSession:output_type -> hulation.v1.chat.ChatSession
	2,  // 36: hulation.v1.chat.ChatService.ReleaseSession:output_type -> hulation.v1.chat.ChatSession
	15, // 37: hulation.v1.chat.ChatService.GetQueue:output_type -> hulation.v1.chat.GetQueueResponse
	18, // 38: hulation.v1.chat.ChatService.GetLiveSessions:output_type -> hulation.v1.chat.GetLiveSessionsResponse
	20, // 39: hulation.v1.chat.ChatService.SearchMessages:output_type -> hulation.v1.chat.SearchMessagesResponse
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_apispec_v1_chat_chat_proto_init() }
func file_pkg_apispec_v1_chat_chat_proto_init() {
	if File_pkg_apispec_v1_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_chat_chat_proto_rawDesc), len(file_pkg_apispec_v1_chat_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apispec_v1_chat_chat_proto_goTypes,
		DependencyIndexes: file_pkg_apispec_v1_chat_chat_proto_depIdxs,
		EnumInfos:         file_pkg_apispec_v1_chat_chat_proto_enumTypes,
		MessageInfos:      file_pkg_apispec_v1_chat_chat_proto_msgTypes,
	}.Build()
	File_pkg_apispec_v1_chat_chat_proto = out.File
	file_pkg_apispec_v1_chat_chat_proto_goTypes = nil
	file_pkg_apispec_v1_chat_chat_proto_depIdxs = nil
}
