// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: pkg/apispec/v1/alerts/alerts.proto

// AlertsService — threshold-alert CRUD + recent-fires listing.
//
// An Alert is a persistent rule evaluated on a 1-minute ticker by the
// Phase-4 evaluator goroutine (pkg/alerts/evaluator). When a rule
// fires, the evaluator writes an AlertEvent row to Bolt, renders an
// email body, and hands it to pkg/mailer for delivery (reusing the
// Phase-3 mailer).
//
// Kinds (AlertKind):
//   GOAL_COUNT_ABOVE      — conversions for target_goal_id in the last
//                           window_minutes > threshold.
//   PAGE_TRAFFIC_DELTA    — pageviews to target_path in the current
//                           window_minutes vs the same window one
//                           week ago; fires when |delta_pct| > threshold.
//   FORM_SUBMISSION_RATE  — submissions to target_form_id per minute
//                           exceed threshold (spam burst detector).
//   BAD_ACTOR_RATE        — bad-actor hits/minute > threshold.
//   BUILD_FAILED          — any build_failed event in window (threshold
//                           ignored).
//
// Writes require server.<id>.admin; reads require
// server.<id>.analytics.read so non-admins can see the rules that
// govern the inbox they already receive.

package alertsspec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertsService_CreateAlert_FullMethodName     = "/hulation.v1.alerts.AlertsService/CreateAlert"
	AlertsService_UpdateAlert_FullMethodName     = "/hulation.v1.alerts.AlertsService/UpdateAlert"
	AlertsService_DeleteAlert_FullMethodName     = "/hulation.v1.alerts.AlertsService/DeleteAlert"
	AlertsService_ListAlerts_FullMethodName      = "/hulation.v1.alerts.AlertsService/ListAlerts"
	AlertsService_GetAlert_FullMethodName        = "/hulation.v1.alerts.AlertsService/GetAlert"
	AlertsService_ListAlertEvents_FullMethodName = "/hulation.v1.alerts.AlertsService/ListAlertEvents"
)

// AlertsServiceClient is the client API for AlertsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertsServiceClient interface {
	CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...grpc.CallOption) (*DeleteAlertResponse, error)
	ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error)
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// ListAlertEvents returns the recent fire history for one alert.
	ListAlertEvents(ctx context.Context, in *ListAlertEventsRequest, opts ...grpc.CallOption) (*ListAlertEventsResponse, error)
}

type alertsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertsServiceClient(cc grpc.ClientConnInterface) AlertsServiceClient {
	return &alertsServiceClient{cc}
}

func (c *alertsServiceClient) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertsService_CreateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsServiceClient) UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertsService_UpdateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsServiceClient) DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...grpc.CallOption) (*DeleteAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAlertResponse)
	err := c.cc.Invoke(ctx, AlertsService_DeleteAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsServiceClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, AlertsService_ListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsServiceClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertsService_GetAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsServiceClient) ListAlertEvents(ctx context.Context, in *ListAlertEventsRequest, opts ...grpc.CallOption) (*ListAlertEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertEventsResponse)
	err := c.cc.Invoke(ctx, AlertsService_ListAlertEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertsServiceServer is the server API for AlertsService service.
// All implementations must embed UnimplementedAlertsServiceServer
// for forward compatibility.
type AlertsServiceServer interface {
	CreateAlert(context.Context, *CreateAlertRequest) (*Alert, error)
	UpdateAlert(context.Context, *UpdateAlertRequest) (*Alert, error)
	DeleteAlert(context.Context, *DeleteAlertRequest) (*DeleteAlertResponse, error)
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	GetAlert(context.Context, *GetAlertRequest) (*Alert, error)
	// ListAlertEvents returns the recent fire history for one alert.
	ListAlertEvents(context.Context, *ListAlertEventsRequest) (*ListAlertEventsResponse, error)
	mustEmbedUnimplementedAlertsServiceServer()
}

// UnimplementedAlertsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertsServiceServer struct{}

func (UnimplementedAlertsServiceServer) CreateAlert(context.Context, *CreateAlertRequest) (*Alert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlert not implemented")
}
func (UnimplementedAlertsServiceServer) UpdateAlert(context.Context, *UpdateAlertRequest) (*Alert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlert not implemented")
}
func (UnimplementedAlertsServiceServer) DeleteAlert(context.Context, *DeleteAlertRequest) (*DeleteAlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlert not implemented")
}
func (UnimplementedAlertsServiceServer) ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlerts not implemented")
}
func (UnimplementedAlertsServiceServer) GetAlert(context.Context, *GetAlertRequest) (*Alert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlert not implemented")
}
func (UnimplementedAlertsServiceServer) ListAlertEvents(context.Context, *ListAlertEventsRequest) (*ListAlertEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlertEvents not implemented")
}
func (UnimplementedAlertsServiceServer) mustEmbedUnimplementedAlertsServiceServer() {}
func (UnimplementedAlertsServiceServer) testEmbeddedByValue()                       {}

// UnsafeAlertsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertsServiceServer will
// result in compilation errors.
type UnsafeAlertsServiceServer interface {
	mustEmbedUnimplementedAlertsServiceServer()
}

func RegisterAlertsServiceServer(s grpc.ServiceRegistrar, srv AlertsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlertsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertsService_ServiceDesc, srv)
}

func _AlertsService_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServiceServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertsService_CreateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServiceServer).CreateAlert(ctx, req.(*CreateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertsService_UpdateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServiceServer).UpdateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertsService_UpdateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServiceServer).UpdateAlert(ctx, req.(*UpdateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertsService_DeleteAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServiceServer).DeleteAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertsService_DeleteAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServiceServer).DeleteAlert(ctx, req.(*DeleteAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertsService_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServiceServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertsService_ListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServiceServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertsService_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServiceServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertsService_GetAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServiceServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertsService_ListAlertEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServiceServer).ListAlertEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertsService_ListAlertEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServiceServer).ListAlertEvents(ctx, req.(*ListAlertEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertsService_ServiceDesc is the grpc.ServiceDesc for AlertsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hulation.v1.alerts.AlertsService",
	HandlerType: (*AlertsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlert",
			Handler:    _AlertsService_CreateAlert_Handler,
		},
		{
			MethodName: "UpdateAlert",
			Handler:    _AlertsService_UpdateAlert_Handler,
		},
		{
			MethodName: "DeleteAlert",
			Handler:    _AlertsService_DeleteAlert_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _AlertsService_ListAlerts_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _AlertsService_GetAlert_Handler,
		},
		{
			MethodName: "ListAlertEvents",
			Handler:    _AlertsService_ListAlertEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apispec/v1/alerts/alerts.proto",
}
