// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: pkg/apispec/v1/mobile/mobile.proto

// MobileService — the compact, phone-sized projection of the
// analytics surface. Endpoints deliberately return smaller payloads
// than the web /summary + /timeseries endpoints: fewer fields,
// bucketised to screen-sized timeseries (12 or 24 points), and with
// device-registration helpers so the mobile app can opt into push
// notifications.
//
// Versioned at `/api/mobile/v1/*` so future breaking changes can
// ship as `v2` without disturbing installed apps.

package mobilespec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MobileService_RegisterDevice_FullMethodName   = "/hulation.v1.mobile.MobileService/RegisterDevice"
	MobileService_UnregisterDevice_FullMethodName = "/hulation.v1.mobile.MobileService/UnregisterDevice"
	MobileService_ListMyDevices_FullMethodName    = "/hulation.v1.mobile.MobileService/ListMyDevices"
	MobileService_MobileSummary_FullMethodName    = "/hulation.v1.mobile.MobileService/MobileSummary"
	MobileService_MobileTimeseries_FullMethodName = "/hulation.v1.mobile.MobileService/MobileTimeseries"
)

// MobileServiceClient is the client API for MobileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MobileServiceClient interface {
	// RegisterDevice records an APNs / FCM token for the caller. The
	// plaintext token is sealed in AES-GCM before persisting (see
	// pkg/mobile/tokenbox). Idempotent: re-registering the same
	// (platform, device_fingerprint) replaces the token.
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*Device, error)
	UnregisterDevice(ctx context.Context, in *UnregisterDeviceRequest, opts ...grpc.CallOption) (*UnregisterDeviceResponse, error)
	// ListMyDevices — caller sees their own devices (no admin flag).
	ListMyDevices(ctx context.Context, in *ListMyDevicesRequest, opts ...grpc.CallOption) (*ListMyDevicesResponse, error)
	// MobileSummary — compact KPI payload. Includes a 12-point
	// sparkline so the app doesn't need a second round-trip for the
	// dashboard card.
	MobileSummary(ctx context.Context, in *MobileSummaryRequest, opts ...grpc.CallOption) (*MobileSummaryResponse, error)
	// MobileTimeseries — bucketised to 12 (hourly) or 24 (daily) points
	// by default. Larger buckets → smaller payload; matches the
	// phone's usable horizontal resolution.
	MobileTimeseries(ctx context.Context, in *MobileTimeseriesRequest, opts ...grpc.CallOption) (*MobileTimeseriesResponse, error)
}

type mobileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMobileServiceClient(cc grpc.ClientConnInterface) MobileServiceClient {
	return &mobileServiceClient{cc}
}

func (c *mobileServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Device)
	err := c.cc.Invoke(ctx, MobileService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileServiceClient) UnregisterDevice(ctx context.Context, in *UnregisterDeviceRequest, opts ...grpc.CallOption) (*UnregisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterDeviceResponse)
	err := c.cc.Invoke(ctx, MobileService_UnregisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileServiceClient) ListMyDevices(ctx context.Context, in *ListMyDevicesRequest, opts ...grpc.CallOption) (*ListMyDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyDevicesResponse)
	err := c.cc.Invoke(ctx, MobileService_ListMyDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileServiceClient) MobileSummary(ctx context.Context, in *MobileSummaryRequest, opts ...grpc.CallOption) (*MobileSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MobileSummaryResponse)
	err := c.cc.Invoke(ctx, MobileService_MobileSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileServiceClient) MobileTimeseries(ctx context.Context, in *MobileTimeseriesRequest, opts ...grpc.CallOption) (*MobileTimeseriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MobileTimeseriesResponse)
	err := c.cc.Invoke(ctx, MobileService_MobileTimeseries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MobileServiceServer is the server API for MobileService service.
// All implementations must embed UnimplementedMobileServiceServer
// for forward compatibility.
type MobileServiceServer interface {
	// RegisterDevice records an APNs / FCM token for the caller. The
	// plaintext token is sealed in AES-GCM before persisting (see
	// pkg/mobile/tokenbox). Idempotent: re-registering the same
	// (platform, device_fingerprint) replaces the token.
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*Device, error)
	UnregisterDevice(context.Context, *UnregisterDeviceRequest) (*UnregisterDeviceResponse, error)
	// ListMyDevices — caller sees their own devices (no admin flag).
	ListMyDevices(context.Context, *ListMyDevicesRequest) (*ListMyDevicesResponse, error)
	// MobileSummary — compact KPI payload. Includes a 12-point
	// sparkline so the app doesn't need a second round-trip for the
	// dashboard card.
	MobileSummary(context.Context, *MobileSummaryRequest) (*MobileSummaryResponse, error)
	// MobileTimeseries — bucketised to 12 (hourly) or 24 (daily) points
	// by default. Larger buckets → smaller payload; matches the
	// phone's usable horizontal resolution.
	MobileTimeseries(context.Context, *MobileTimeseriesRequest) (*MobileTimeseriesResponse, error)
	mustEmbedUnimplementedMobileServiceServer()
}

// UnimplementedMobileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMobileServiceServer struct{}

func (UnimplementedMobileServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedMobileServiceServer) UnregisterDevice(context.Context, *UnregisterDeviceRequest) (*UnregisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterDevice not implemented")
}
func (UnimplementedMobileServiceServer) ListMyDevices(context.Context, *ListMyDevicesRequest) (*ListMyDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyDevices not implemented")
}
func (UnimplementedMobileServiceServer) MobileSummary(context.Context, *MobileSummaryRequest) (*MobileSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MobileSummary not implemented")
}
func (UnimplementedMobileServiceServer) MobileTimeseries(context.Context, *MobileTimeseriesRequest) (*MobileTimeseriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MobileTimeseries not implemented")
}
func (UnimplementedMobileServiceServer) mustEmbedUnimplementedMobileServiceServer() {}
func (UnimplementedMobileServiceServer) testEmbeddedByValue()                       {}

// UnsafeMobileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MobileServiceServer will
// result in compilation errors.
type UnsafeMobileServiceServer interface {
	mustEmbedUnimplementedMobileServiceServer()
}

func RegisterMobileServiceServer(s grpc.ServiceRegistrar, srv MobileServiceServer) {
	// If the following call pancis, it indicates UnimplementedMobileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MobileService_ServiceDesc, srv)
}

func _MobileService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobileService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileService_UnregisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServiceServer).UnregisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobileService_UnregisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServiceServer).UnregisterDevice(ctx, req.(*UnregisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileService_ListMyDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServiceServer).ListMyDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobileService_ListMyDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServiceServer).ListMyDevices(ctx, req.(*ListMyDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileService_MobileSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MobileSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServiceServer).MobileSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobileService_MobileSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServiceServer).MobileSummary(ctx, req.(*MobileSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileService_MobileTimeseries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MobileTimeseriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServiceServer).MobileTimeseries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobileService_MobileTimeseries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServiceServer).MobileTimeseries(ctx, req.(*MobileTimeseriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MobileService_ServiceDesc is the grpc.ServiceDesc for MobileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MobileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hulation.v1.mobile.MobileService",
	HandlerType: (*MobileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _MobileService_RegisterDevice_Handler,
		},
		{
			MethodName: "UnregisterDevice",
			Handler:    _MobileService_UnregisterDevice_Handler,
		},
		{
			MethodName: "ListMyDevices",
			Handler:    _MobileService_ListMyDevices_Handler,
		},
		{
			MethodName: "MobileSummary",
			Handler:    _MobileService_MobileSummary_Handler,
		},
		{
			MethodName: "MobileTimeseries",
			Handler:    _MobileService_MobileTimeseries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apispec/v1/mobile/mobile.proto",
}
