// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: pkg/apispec/v1/internalapi/gossip.proto

// GossipService — push-on-write + periodic anti-entropy for the
// CRDT visitor / session / bad-actor layer (HA_PLAN3 §7). Stage
// 3.7 fills in the merge logic; Stage 3.2 just lands the proto.

package internalapispec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GossipService_Push_FullMethodName       = "/hulation.v1.internalapi.GossipService/Push"
	GossipService_SyncDigest_FullMethodName = "/hulation.v1.internalapi.GossipService/SyncDigest"
)

// GossipServiceClient is the client API for GossipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GossipServiceClient interface {
	// Push fans out an immediate write delta to every peer. The push
	// is fire-and-forget from the writer's perspective; missed pushes
	// are healed by SyncDigest.
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	// SyncDigest exchanges per-bucket high-water HLCs between two
	// peers. The peer with newer entries returns them in deltas.
	SyncDigest(ctx context.Context, in *SyncDigestRequest, opts ...grpc.CallOption) (*SyncDigestResponse, error)
}

type gossipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGossipServiceClient(cc grpc.ClientConnInterface) GossipServiceClient {
	return &gossipServiceClient{cc}
}

func (c *gossipServiceClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, GossipService_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipServiceClient) SyncDigest(ctx context.Context, in *SyncDigestRequest, opts ...grpc.CallOption) (*SyncDigestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDigestResponse)
	err := c.cc.Invoke(ctx, GossipService_SyncDigest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipServiceServer is the server API for GossipService service.
// All implementations must embed UnimplementedGossipServiceServer
// for forward compatibility.
type GossipServiceServer interface {
	// Push fans out an immediate write delta to every peer. The push
	// is fire-and-forget from the writer's perspective; missed pushes
	// are healed by SyncDigest.
	Push(context.Context, *PushRequest) (*PushResponse, error)
	// SyncDigest exchanges per-bucket high-water HLCs between two
	// peers. The peer with newer entries returns them in deltas.
	SyncDigest(context.Context, *SyncDigestRequest) (*SyncDigestResponse, error)
	mustEmbedUnimplementedGossipServiceServer()
}

// UnimplementedGossipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGossipServiceServer struct{}

func (UnimplementedGossipServiceServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedGossipServiceServer) SyncDigest(context.Context, *SyncDigestRequest) (*SyncDigestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncDigest not implemented")
}
func (UnimplementedGossipServiceServer) mustEmbedUnimplementedGossipServiceServer() {}
func (UnimplementedGossipServiceServer) testEmbeddedByValue()                       {}

// UnsafeGossipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GossipServiceServer will
// result in compilation errors.
type UnsafeGossipServiceServer interface {
	mustEmbedUnimplementedGossipServiceServer()
}

func RegisterGossipServiceServer(s grpc.ServiceRegistrar, srv GossipServiceServer) {
	// If the following call pancis, it indicates UnimplementedGossipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GossipService_ServiceDesc, srv)
}

func _GossipService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipService_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipService_SyncDigest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDigestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).SyncDigest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipService_SyncDigest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).SyncDigest(ctx, req.(*SyncDigestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GossipService_ServiceDesc is the grpc.ServiceDesc for GossipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GossipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hulation.v1.internalapi.GossipService",
	HandlerType: (*GossipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _GossipService_Push_Handler,
		},
		{
			MethodName: "SyncDigest",
			Handler:    _GossipService_SyncDigest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apispec/v1/internalapi/gossip.proto",
}
