// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/apispec/v1/internalapi/membership.proto

// MembershipService — internal-only RPC for joining/leaving the
// Team's Raft cluster. Mounted on the unified listener behind the
// Team-CA mTLS gate; never exposed on the public REST gateway.
//
// See HA_PLAN3.md §3 for the join handshake design.

package internalapispec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TeamId         string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr       string                 `protobuf:"bytes,3,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	BootstrapToken string                 `protobuf:"bytes,4,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	ChConnected    bool                   `protobuf:"varint,5,opt,name=ch_connected,json=chConnected,proto3" json:"ch_connected,omitempty"`
	NodeHostname   string                 `protobuf:"bytes,6,opt,name=node_hostname,json=nodeHostname,proto3" json:"node_hostname,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_membership_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *JoinRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *JoinRequest) GetChConnected() bool {
	if x != nil {
		return x.ChConnected
	}
	return false
}

func (x *JoinRequest) GetNodeHostname() string {
	if x != nil {
		return x.NodeHostname
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	LastIndex     uint64                 `protobuf:"varint,3,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_membership_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *JoinResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *JoinResponse) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_membership_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *LeaveRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type LeaveResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LeadershipTransferred bool                   `protobuf:"varint,1,opt,name=leadership_transferred,json=leadershipTransferred,proto3" json:"leadership_transferred,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_membership_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveResponse) GetLeadershipTransferred() bool {
	if x != nil {
		return x.LeadershipTransferred
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_membership_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	LastIndex     uint64                 `protobuf:"varint,3,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	AppliedIndex  uint64                 `protobuf:"varint,4,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	HasQuorum     bool                   `protobuf:"varint,5,opt,name=has_quorum,json=hasQuorum,proto3" json:"has_quorum,omitempty"`
	Members       []*MemberInfo          `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_membership_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *StatusResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *StatusResponse) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

func (x *StatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetHasQuorum() bool {
	if x != nil {
		return x.HasQuorum
	}
	return false
}

func (x *StatusResponse) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	Suffrage      string                 `protobuf:"bytes,3,opt,name=suffrage,proto3" json:"suffrage,omitempty"` // "voter" | "nonvoter" | "staging"
	ChConnected   bool                   `protobuf:"varint,4,opt,name=ch_connected,json=chConnected,proto3" json:"ch_connected,omitempty"`
	IsLeader      bool                   `protobuf:"varint,5,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_membership_proto_rawDescGZIP(), []int{6}
}

func (x *MemberInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MemberInfo) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *MemberInfo) GetSuffrage() string {
	if x != nil {
		return x.Suffrage
	}
	return ""
}

func (x *MemberInfo) GetChConnected() bool {
	if x != nil {
		return x.ChConnected
	}
	return false
}

func (x *MemberInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

var File_pkg_apispec_v1_internalapi_membership_proto protoreflect.FileDescriptor

const file_pkg_apispec_v1_internalapi_membership_proto_rawDesc = "" +
	"\n" +
	"+pkg/apispec/v1/internalapi/membership.proto\x12\x17hulation.v1.internalapi\"\xcd\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x03 \x01(\tR\braftAddr\x12'\n" +
	"\x0fbootstrap_token\x18\x04 \x01(\tR\x0ebootstrapToken\x12!\n" +
	"\fch_connected\x18\x05 \x01(\bR\vchConnected\x12#\n" +
	"\rnode_hostname\x18\x06 \x01(\tR\fnodeHostname\"k\n" +
	"\fJoinResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\x12\x1d\n" +
	"\n" +
	"last_index\x18\x03 \x01(\x04R\tlastIndex\"@\n" +
	"\fLeaveRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"F\n" +
	"\rLeaveResponse\x125\n" +
	"\x16leadership_transferred\x18\x01 \x01(\bR\x15leadershipTransferred\"\x0f\n" +
	"\rStatusRequest\"\xf0\x01\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\x12\x1d\n" +
	"\n" +
	"last_index\x18\x03 \x01(\x04R\tlastIndex\x12#\n" +
	"\rapplied_index\x18\x04 \x01(\x04R\fappliedIndex\x12\x1d\n" +
	"\n" +
	"has_quorum\x18\x05 \x01(\bR\thasQuorum\x12=\n" +
	"\amembers\x18\x06 \x03(\v2#.hulation.v1.internalapi.MemberInfoR\amembers\"\x9e\x01\n" +
	"\n" +
	"MemberInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x1a\n" +
	"\bsuffrage\x18\x03 \x01(\tR\bsuffrage\x12!\n" +
	"\fch_connected\x18\x04 \x01(\bR\vchConnected\x12\x1b\n" +
	"\tis_leader\x18\x05 \x01(\bR\bisLeader2\x9b\x02\n" +
	"\x11MembershipService\x12S\n" +
	"\x04Join\x12$.hulation.v1.internalapi.JoinRequest\x1a%.hulation.v1.internalapi.JoinResponse\x12V\n" +
	"\x05Leave\x12%.hulation.v1.internalapi.LeaveRequest\x1a&.hulation.v1.internalapi.LeaveResponse\x12Y\n" +
	"\x06Status\x12&.hulation.v1.internalapi.StatusRequest\x1a'.hulation.v1.internalapi.StatusResponseBJZHgithub.com/tlalocweb/hulation/pkg/apispec/v1/internalapi;internalapispecb\x06proto3"

var (
	file_pkg_apispec_v1_internalapi_membership_proto_rawDescOnce sync.Once
	file_pkg_apispec_v1_internalapi_membership_proto_rawDescData []byte
)

func file_pkg_apispec_v1_internalapi_membership_proto_rawDescGZIP() []byte {
	file_pkg_apispec_v1_internalapi_membership_proto_rawDescOnce.Do(func() {
		file_pkg_apispec_v1_internalapi_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_internalapi_membership_proto_rawDesc), len(file_pkg_apispec_v1_internalapi_membership_proto_rawDesc)))
	})
	return file_pkg_apispec_v1_internalapi_membership_proto_rawDescData
}

var file_pkg_apispec_v1_internalapi_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_apispec_v1_internalapi_membership_proto_goTypes = []any{
	(*JoinRequest)(nil),    // 0: hulation.v1.internalapi.JoinRequest
	(*JoinResponse)(nil),   // 1: hulation.v1.internalapi.JoinResponse
	(*LeaveRequest)(nil),   // 2: hulation.v1.internalapi.LeaveRequest
	(*LeaveResponse)(nil),  // 3: hulation.v1.internalapi.LeaveResponse
	(*StatusRequest)(nil),  // 4: hulation.v1.internalapi.StatusRequest
	(*StatusResponse)(nil), // 5: hulation.v1.internalapi.StatusResponse
	(*MemberInfo)(nil),     // 6: hulation.v1.internalapi.MemberInfo
}
var file_pkg_apispec_v1_internalapi_membership_proto_depIdxs = []int32{
	6, // 0: hulation.v1.internalapi.StatusResponse.members:type_name -> hulation.v1.internalapi.MemberInfo
	0, // 1: hulation.v1.internalapi.MembershipService.Join:input_type -> hulation.v1.internalapi.JoinRequest
	2, // 2: hulation.v1.internalapi.MembershipService.Leave:input_type -> hulation.v1.internalapi.LeaveRequest
	4, // 3: hulation.v1.internalapi.MembershipService.Status:input_type -> hulation.v1.internalapi.StatusRequest
	1, // 4: hulation.v1.internalapi.MembershipService.Join:output_type -> hulation.v1.internalapi.JoinResponse
	3, // 5: hulation.v1.internalapi.MembershipService.Leave:output_type -> hulation.v1.internalapi.LeaveResponse
	5, // 6: hulation.v1.internalapi.MembershipService.Status:output_type -> hulation.v1.internalapi.StatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_apispec_v1_internalapi_membership_proto_init() }
func file_pkg_apispec_v1_internalapi_membership_proto_init() {
	if File_pkg_apispec_v1_internalapi_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_internalapi_membership_proto_rawDesc), len(file_pkg_apispec_v1_internalapi_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apispec_v1_internalapi_membership_proto_goTypes,
		DependencyIndexes: file_pkg_apispec_v1_internalapi_membership_proto_depIdxs,
		MessageInfos:      file_pkg_apispec_v1_internalapi_membership_proto_msgTypes,
	}.Build()
	File_pkg_apispec_v1_internalapi_membership_proto = out.File
	file_pkg_apispec_v1_internalapi_membership_proto_goTypes = nil
	file_pkg_apispec_v1_internalapi_membership_proto_depIdxs = nil
}
