// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: pkg/apispec/v1/internalapi/raftransport.proto

// RaftTransportService wraps hashicorp/raft's transport contract in
// a single bidirectional streaming RPC so Raft RPCs ride the same
// unified HTTPS port as everything else. Stage 3.3 fills in the
// stream codec; Stage 3.2 lands the proto + a stub.

package internalapispec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftTransportService_Stream_FullMethodName = "/hulation.v1.internalapi.RaftTransportService/Stream"
)

// RaftTransportServiceClient is the client API for RaftTransportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftTransportServiceClient interface {
	// Stream carries one Raft RPC per stream. The first frame is
	// the request (AppendEntries / RequestVote / InstallSnapshot /
	// TimeoutNow). The server replies with one or more frames
	// depending on the RPC kind (InstallSnapshot streams chunks).
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RaftFrame, RaftFrame], error)
}

type raftTransportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftTransportServiceClient(cc grpc.ClientConnInterface) RaftTransportServiceClient {
	return &raftTransportServiceClient{cc}
}

func (c *raftTransportServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RaftFrame, RaftFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftTransportService_ServiceDesc.Streams[0], RaftTransportService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RaftFrame, RaftFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftTransportService_StreamClient = grpc.BidiStreamingClient[RaftFrame, RaftFrame]

// RaftTransportServiceServer is the server API for RaftTransportService service.
// All implementations must embed UnimplementedRaftTransportServiceServer
// for forward compatibility.
type RaftTransportServiceServer interface {
	// Stream carries one Raft RPC per stream. The first frame is
	// the request (AppendEntries / RequestVote / InstallSnapshot /
	// TimeoutNow). The server replies with one or more frames
	// depending on the RPC kind (InstallSnapshot streams chunks).
	Stream(grpc.BidiStreamingServer[RaftFrame, RaftFrame]) error
	mustEmbedUnimplementedRaftTransportServiceServer()
}

// UnimplementedRaftTransportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftTransportServiceServer struct{}

func (UnimplementedRaftTransportServiceServer) Stream(grpc.BidiStreamingServer[RaftFrame, RaftFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRaftTransportServiceServer) mustEmbedUnimplementedRaftTransportServiceServer() {}
func (UnimplementedRaftTransportServiceServer) testEmbeddedByValue()                              {}

// UnsafeRaftTransportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftTransportServiceServer will
// result in compilation errors.
type UnsafeRaftTransportServiceServer interface {
	mustEmbedUnimplementedRaftTransportServiceServer()
}

func RegisterRaftTransportServiceServer(s grpc.ServiceRegistrar, srv RaftTransportServiceServer) {
	// If the following call pancis, it indicates UnimplementedRaftTransportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftTransportService_ServiceDesc, srv)
}

func _RaftTransportService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftTransportServiceServer).Stream(&grpc.GenericServerStream[RaftFrame, RaftFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftTransportService_StreamServer = grpc.BidiStreamingServer[RaftFrame, RaftFrame]

// RaftTransportService_ServiceDesc is the grpc.ServiceDesc for RaftTransportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftTransportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hulation.v1.internalapi.RaftTransportService",
	HandlerType: (*RaftTransportServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _RaftTransportService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/apispec/v1/internalapi/raftransport.proto",
}
