// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/apispec/v1/internalapi/storageproxy.proto

// StorageProxyService — followers forward Raft writes to the leader
// over this RPC (HA_PLAN3 §9). Stage 3.5 fills in the apply path;
// Stage 3.2 just lands the proto + a stub.

package internalapispec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is the proto-encoded RaftCommand from
	// pkg/store/storage/raft/cmd.proto. Followers serialise once and
	// hand it through to the leader's r.Apply().
	Command       []byte `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_pkg_apispec_v1_internalapi_storageproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_storageproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type ApplyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// applied_index is the Raft index assigned to this command after
	// the leader committed it; used by the caller as a synchronization
	// hint (read-after-write).
	AppliedIndex  uint64 `protobuf:"varint,1,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_pkg_apispec_v1_internalapi_storageproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_internalapi_storageproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

var File_pkg_apispec_v1_internalapi_storageproxy_proto protoreflect.FileDescriptor

const file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDesc = "" +
	"\n" +
	"-pkg/apispec/v1/internalapi/storageproxy.proto\x12\x17hulation.v1.internalapi\"(\n" +
	"\fApplyRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\fR\acommand\"4\n" +
	"\rApplyResponse\x12#\n" +
	"\rapplied_index\x18\x01 \x01(\x04R\fappliedIndex2m\n" +
	"\x13StorageProxyService\x12V\n" +
	"\x05Apply\x12%.hulation.v1.internalapi.ApplyRequest\x1a&.hulation.v1.internalapi.ApplyResponseBJZHgithub.com/tlalocweb/hulation/pkg/apispec/v1/internalapi;internalapispecb\x06proto3"

var (
	file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDescOnce sync.Once
	file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDescData []byte
)

func file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDescGZIP() []byte {
	file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDescOnce.Do(func() {
		file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDesc), len(file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDesc)))
	})
	return file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDescData
}

var file_pkg_apispec_v1_internalapi_storageproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_apispec_v1_internalapi_storageproxy_proto_goTypes = []any{
	(*ApplyRequest)(nil),  // 0: hulation.v1.internalapi.ApplyRequest
	(*ApplyResponse)(nil), // 1: hulation.v1.internalapi.ApplyResponse
}
var file_pkg_apispec_v1_internalapi_storageproxy_proto_depIdxs = []int32{
	0, // 0: hulation.v1.internalapi.StorageProxyService.Apply:input_type -> hulation.v1.internalapi.ApplyRequest
	1, // 1: hulation.v1.internalapi.StorageProxyService.Apply:output_type -> hulation.v1.internalapi.ApplyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_apispec_v1_internalapi_storageproxy_proto_init() }
func file_pkg_apispec_v1_internalapi_storageproxy_proto_init() {
	if File_pkg_apispec_v1_internalapi_storageproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDesc), len(file_pkg_apispec_v1_internalapi_storageproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apispec_v1_internalapi_storageproxy_proto_goTypes,
		DependencyIndexes: file_pkg_apispec_v1_internalapi_storageproxy_proto_depIdxs,
		MessageInfos:      file_pkg_apispec_v1_internalapi_storageproxy_proto_msgTypes,
	}.Build()
	File_pkg_apispec_v1_internalapi_storageproxy_proto = out.File
	file_pkg_apispec_v1_internalapi_storageproxy_proto_goTypes = nil
	file_pkg_apispec_v1_internalapi_storageproxy_proto_depIdxs = nil
}
