// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/apispec/v1/badactor/badactor.proto

// BadActorService — anti-abuse admin APIs.

package badactorspec

import (
	_ "github.com/tlalocweb/hulation/protoext/hula/auth"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BadActor struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ip     string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// country_code from IP geo lookup.
	CountryCode string `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Asn         string `protobuf:"bytes,4,opt,name=asn,proto3" json:"asn,omitempty"`
	Org         string `protobuf:"bytes,5,opt,name=org,proto3" json:"org,omitempty"`
	// hit_count — number of times this IP tripped a signature.
	HitCount  int64                  `protobuf:"varint,6,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	FirstSeen *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// signature_id — which rule matched (if blocked automatically).
	SignatureId string `protobuf:"bytes,9,opt,name=signature_id,json=signatureId,proto3" json:"signature_id,omitempty"`
	// manual — true when the block was added by an operator, not a signature.
	Manual        bool `protobuf:"varint,10,opt,name=manual,proto3" json:"manual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadActor) Reset() {
	*x = BadActor{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadActor) ProtoMessage() {}

func (x *BadActor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadActor.ProtoReflect.Descriptor instead.
func (*BadActor) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{0}
}

func (x *BadActor) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BadActor) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BadActor) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *BadActor) GetAsn() string {
	if x != nil {
		return x.Asn
	}
	return ""
}

func (x *BadActor) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *BadActor) GetHitCount() int64 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *BadActor) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *BadActor) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *BadActor) GetSignatureId() string {
	if x != nil {
		return x.SignatureId
	}
	return ""
}

func (x *BadActor) GetManual() bool {
	if x != nil {
		return x.Manual
	}
	return false
}

type AllowlistEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AddedBy       string                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	AddedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowlistEntry) Reset() {
	*x = AllowlistEntry{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowlistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowlistEntry) ProtoMessage() {}

func (x *AllowlistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowlistEntry.ProtoReflect.Descriptor instead.
func (*AllowlistEntry) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{1}
}

func (x *AllowlistEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllowlistEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AllowlistEntry) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

func (x *AllowlistEntry) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

type Signature struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// pattern is the regex / glob matched against paths, UAs, etc.
	Pattern string `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// target: path, ua, query, method
	Target string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// severity: log, rate_limit, block
	Severity      string `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{2}
}

func (x *Signature) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Signature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Signature) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Signature) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Signature) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type ListBadActorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBadActorsRequest) Reset() {
	*x = ListBadActorsRequest{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBadActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBadActorsRequest) ProtoMessage() {}

func (x *ListBadActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBadActorsRequest.ProtoReflect.Descriptor instead.
func (*ListBadActorsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{3}
}

func (x *ListBadActorsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListBadActorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBadActorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*BadActor            `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBadActorsResponse) Reset() {
	*x = ListBadActorsResponse{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBadActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBadActorsResponse) ProtoMessage() {}

func (x *ListBadActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBadActorsResponse.ProtoReflect.Descriptor instead.
func (*ListBadActorsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{4}
}

func (x *ListBadActorsResponse) GetActors() []*BadActor {
	if x != nil {
		return x.Actors
	}
	return nil
}

type ManualBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualBlockRequest) Reset() {
	*x = ManualBlockRequest{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualBlockRequest) ProtoMessage() {}

func (x *ManualBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualBlockRequest.ProtoReflect.Descriptor instead.
func (*ManualBlockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{5}
}

func (x *ManualBlockRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ManualBlockRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ManualBlockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ManualBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *BadActor              `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualBlockResponse) Reset() {
	*x = ManualBlockResponse{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualBlockResponse) ProtoMessage() {}

func (x *ManualBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualBlockResponse.ProtoReflect.Descriptor instead.
func (*ManualBlockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{6}
}

func (x *ManualBlockResponse) GetActor() *BadActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type EvictBadActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictBadActorRequest) Reset() {
	*x = EvictBadActorRequest{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictBadActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictBadActorRequest) ProtoMessage() {}

func (x *EvictBadActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictBadActorRequest.ProtoReflect.Descriptor instead.
func (*EvictBadActorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{7}
}

func (x *EvictBadActorRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *EvictBadActorRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type EvictBadActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictBadActorResponse) Reset() {
	*x = EvictBadActorResponse{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictBadActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictBadActorResponse) ProtoMessage() {}

func (x *EvictBadActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictBadActorResponse.ProtoReflect.Descriptor instead.
func (*EvictBadActorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{8}
}

func (x *EvictBadActorResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListAllowlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllowlistRequest) Reset() {
	*x = ListAllowlistRequest{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllowlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllowlistRequest) ProtoMessage() {}

func (x *ListAllowlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllowlistRequest.ProtoReflect.Descriptor instead.
func (*ListAllowlistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{9}
}

func (x *ListAllowlistRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ListAllowlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AllowlistEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllowlistResponse) Reset() {
	*x = ListAllowlistResponse{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllowlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllowlistResponse) ProtoMessage() {}

func (x *ListAllowlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllowlistResponse.ProtoReflect.Descriptor instead.
func (*ListAllowlistResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{10}
}

func (x *ListAllowlistResponse) GetEntries() []*AllowlistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AddToAllowlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToAllowlistRequest) Reset() {
	*x = AddToAllowlistRequest{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToAllowlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToAllowlistRequest) ProtoMessage() {}

func (x *AddToAllowlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToAllowlistRequest.ProtoReflect.Descriptor instead.
func (*AddToAllowlistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{11}
}

func (x *AddToAllowlistRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AddToAllowlistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddToAllowlistRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AddToAllowlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *AllowlistEntry        `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToAllowlistResponse) Reset() {
	*x = AddToAllowlistResponse{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToAllowlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToAllowlistResponse) ProtoMessage() {}

func (x *AddToAllowlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToAllowlistResponse.ProtoReflect.Descriptor instead.
func (*AddToAllowlistResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{12}
}

func (x *AddToAllowlistResponse) GetEntry() *AllowlistEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type RemoveFromAllowlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromAllowlistRequest) Reset() {
	*x = RemoveFromAllowlistRequest{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromAllowlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromAllowlistRequest) ProtoMessage() {}

func (x *RemoveFromAllowlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromAllowlistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromAllowlistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveFromAllowlistRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RemoveFromAllowlistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RemoveFromAllowlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromAllowlistResponse) Reset() {
	*x = RemoveFromAllowlistResponse{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromAllowlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromAllowlistResponse) ProtoMessage() {}

func (x *RemoveFromAllowlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromAllowlistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromAllowlistResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveFromAllowlistResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type BadActorStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadActorStatsRequest) Reset() {
	*x = BadActorStatsRequest{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadActorStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadActorStatsRequest) ProtoMessage() {}

func (x *BadActorStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadActorStatsRequest.ProtoReflect.Descriptor instead.
func (*BadActorStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{15}
}

func (x *BadActorStatsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type BadActorStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockedTotal    int64                  `protobuf:"varint,1,opt,name=blocked_total,json=blockedTotal,proto3" json:"blocked_total,omitempty"`
	BlockedLast_24H int64                  `protobuf:"varint,2,opt,name=blocked_last_24h,json=blockedLast24h,proto3" json:"blocked_last_24h,omitempty"`
	AllowlistSize   int64                  `protobuf:"varint,3,opt,name=allowlist_size,json=allowlistSize,proto3" json:"allowlist_size,omitempty"`
	// top_sources_24h — ASN/country buckets for observability.
	TopSources_24H []*StatBucket `protobuf:"bytes,4,rep,name=top_sources_24h,json=topSources24h,proto3" json:"top_sources_24h,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BadActorStatsResponse) Reset() {
	*x = BadActorStatsResponse{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadActorStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadActorStatsResponse) ProtoMessage() {}

func (x *BadActorStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadActorStatsResponse.ProtoReflect.Descriptor instead.
func (*BadActorStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{16}
}

func (x *BadActorStatsResponse) GetBlockedTotal() int64 {
	if x != nil {
		return x.BlockedTotal
	}
	return 0
}

func (x *BadActorStatsResponse) GetBlockedLast_24H() int64 {
	if x != nil {
		return x.BlockedLast_24H
	}
	return 0
}

func (x *BadActorStatsResponse) GetAllowlistSize() int64 {
	if x != nil {
		return x.AllowlistSize
	}
	return 0
}

func (x *BadActorStatsResponse) GetTopSources_24H() []*StatBucket {
	if x != nil {
		return x.TopSources_24H
	}
	return nil
}

type StatBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatBucket) Reset() {
	*x = StatBucket{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatBucket) ProtoMessage() {}

func (x *StatBucket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatBucket.ProtoReflect.Descriptor instead.
func (*StatBucket) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{17}
}

func (x *StatBucket) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StatBucket) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListSignaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSignaturesRequest) Reset() {
	*x = ListSignaturesRequest{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSignaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSignaturesRequest) ProtoMessage() {}

func (x *ListSignaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSignaturesRequest.ProtoReflect.Descriptor instead.
func (*ListSignaturesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{18}
}

type ListSignaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    []*Signature           `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSignaturesResponse) Reset() {
	*x = ListSignaturesResponse{}
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSignaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSignaturesResponse) ProtoMessage() {}

func (x *ListSignaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_badactor_badactor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSignaturesResponse.ProtoReflect.Descriptor instead.
func (*ListSignaturesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP(), []int{19}
}

func (x *ListSignaturesResponse) GetSignatures() []*Signature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

var File_pkg_apispec_v1_badactor_badactor_proto protoreflect.FileDescriptor

const file_pkg_apispec_v1_badactor_badactor_proto_rawDesc = "" +
	"\n" +
	"&pkg/apispec/v1/badactor/badactor.proto\x12\x14hulation.v1.badactor\x1a\x1cgoogle/api/annotations.proto\x1a\x1ahula/auth/permission.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x02\n" +
	"\bBadActor\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12\x10\n" +
	"\x03asn\x18\x04 \x01(\tR\x03asn\x12\x10\n" +
	"\x03org\x18\x05 \x01(\tR\x03org\x12\x1b\n" +
	"\thit_count\x18\x06 \x01(\x03R\bhitCount\x129\n" +
	"\n" +
	"first_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12!\n" +
	"\fsignature_id\x18\t \x01(\tR\vsignatureId\x12\x16\n" +
	"\x06manual\x18\n" +
	" \x01(\bR\x06manual\"\x8a\x01\n" +
	"\x0eAllowlistEntry\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\tR\aaddedBy\x125\n" +
	"\badded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\"\x8b\x01\n" +
	"\tSignature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\"I\n" +
	"\x14ListBadActorsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"O\n" +
	"\x15ListBadActorsResponse\x126\n" +
	"\x06actors\x18\x01 \x03(\v2\x1e.hulation.v1.badactor.BadActorR\x06actors\"Y\n" +
	"\x12ManualBlockRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"K\n" +
	"\x13ManualBlockResponse\x124\n" +
	"\x05actor\x18\x01 \x01(\v2\x1e.hulation.v1.badactor.BadActorR\x05actor\"C\n" +
	"\x14EvictBadActorRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"'\n" +
	"\x15EvictBadActorResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"3\n" +
	"\x14ListAllowlistRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"W\n" +
	"\x15ListAllowlistResponse\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.hulation.v1.badactor.AllowlistEntryR\aentries\"\\\n" +
	"\x15AddToAllowlistRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"T\n" +
	"\x16AddToAllowlistResponse\x12:\n" +
	"\x05entry\x18\x01 \x01(\v2$.hulation.v1.badactor.AllowlistEntryR\x05entry\"I\n" +
	"\x1aRemoveFromAllowlistRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"-\n" +
	"\x1bRemoveFromAllowlistResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"3\n" +
	"\x14BadActorStatsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\xd7\x01\n" +
	"\x15BadActorStatsResponse\x12#\n" +
	"\rblocked_total\x18\x01 \x01(\x03R\fblockedTotal\x12(\n" +
	"\x10blocked_last_24h\x18\x02 \x01(\x03R\x0eblockedLast24h\x12%\n" +
	"\x0eallowlist_size\x18\x03 \x01(\x03R\rallowlistSize\x12H\n" +
	"\x0ftop_sources_24h\x18\x04 \x03(\v2 .hulation.v1.badactor.StatBucketR\rtopSources24h\"4\n" +
	"\n" +
	"StatBucket\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\x17\n" +
	"\x15ListSignaturesRequest\"Y\n" +
	"\x16ListSignaturesResponse\x12?\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v2\x1f.hulation.v1.badactor.SignatureR\n" +
	"signatures2\xd4\v\n" +
	"\x0fBadActorService\x12\xab\x01\n" +
	"\rListBadActors\x12*.hulation.v1.badactor.ListBadActorsRequest\x1a+.hulation.v1.badactor.ListBadActorsResponse\"Aҵ\x18$\n" +
	"\"server.{server_id}.badactor.manage\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/badactors\x12\xae\x01\n" +
	"\vManualBlock\x12(.hulation.v1.badactor.ManualBlockRequest\x1a).hulation.v1.badactor.ManualBlockResponse\"Jҵ\x18$\n" +
	"\"server.{server_id}.badactor.manage\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/badactors/block\x12\xb6\x01\n" +
	"\rEvictBadActor\x12*.hulation.v1.badactor.EvictBadActorRequest\x1a+.hulation.v1.badactor.EvictBadActorResponse\"Lҵ\x18$\n" +
	"\"server.{server_id}.badactor.manage\x82\xd3\xe4\x93\x02\x1e*\x1c/api/v1/badactors/block/{ip}\x12\xb5\x01\n" +
	"\rListAllowlist\x12*.hulation.v1.badactor.ListAllowlistRequest\x1a+.hulation.v1.badactor.ListAllowlistResponse\"Kҵ\x18$\n" +
	"\"server.{server_id}.badactor.manage\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/badactors/allowlist\x12\xbb\x01\n" +
	"\x0eAddToAllowlist\x12+.hulation.v1.badactor.AddToAllowlistRequest\x1a,.hulation.v1.badactor.AddToAllowlistResponse\"Nҵ\x18$\n" +
	"\"server.{server_id}.badactor.manage\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/badactors/allowlist\x12\xcc\x01\n" +
	"\x13RemoveFromAllowlist\x120.hulation.v1.badactor.RemoveFromAllowlistRequest\x1a1.hulation.v1.badactor.RemoveFromAllowlistResponse\"Pҵ\x18$\n" +
	"\"server.{server_id}.badactor.manage\x82\xd3\xe4\x93\x02\"* /api/v1/badactors/allowlist/{ip}\x12\xb1\x01\n" +
	"\rBadActorStats\x12*.hulation.v1.badactor.BadActorStatsRequest\x1a+.hulation.v1.badactor.BadActorStatsResponse\"Gҵ\x18$\n" +
	"\"server.{server_id}.badactor.manage\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/badactors/stats\x12\xaf\x01\n" +
	"\x0eListSignatures\x12+.hulation.v1.badactor.ListSignaturesRequest\x1a,.hulation.v1.badactor.ListSignaturesResponse\"Bҵ\x18\x1a\n" +
	"\x18superadmin.badactor.read\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/badactors/signaturesBDZBgithub.com/tlalocweb/hulation/pkg/apispec/v1/badactor;badactorspecb\x06proto3"

var (
	file_pkg_apispec_v1_badactor_badactor_proto_rawDescOnce sync.Once
	file_pkg_apispec_v1_badactor_badactor_proto_rawDescData []byte
)

func file_pkg_apispec_v1_badactor_badactor_proto_rawDescGZIP() []byte {
	file_pkg_apispec_v1_badactor_badactor_proto_rawDescOnce.Do(func() {
		file_pkg_apispec_v1_badactor_badactor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_badactor_badactor_proto_rawDesc), len(file_pkg_apispec_v1_badactor_badactor_proto_rawDesc)))
	})
	return file_pkg_apispec_v1_badactor_badactor_proto_rawDescData
}

var file_pkg_apispec_v1_badactor_badactor_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_apispec_v1_badactor_badactor_proto_goTypes = []any{
	(*BadActor)(nil),                    // 0: hulation.v1.badactor.BadActor
	(*AllowlistEntry)(nil),              // 1: hulation.v1.badactor.AllowlistEntry
	(*Signature)(nil),                   // 2: hulation.v1.badactor.Signature
	(*ListBadActorsRequest)(nil),        // 3: hulation.v1.badactor.ListBadActorsRequest
	(*ListBadActorsResponse)(nil),       // 4: hulation.v1.badactor.ListBadActorsResponse
	(*ManualBlockRequest)(nil),          // 5: hulation.v1.badactor.ManualBlockRequest
	(*ManualBlockResponse)(nil),         // 6: hulation.v1.badactor.ManualBlockResponse
	(*EvictBadActorRequest)(nil),        // 7: hulation.v1.badactor.EvictBadActorRequest
	(*EvictBadActorResponse)(nil),       // 8: hulation.v1.badactor.EvictBadActorResponse
	(*ListAllowlistRequest)(nil),        // 9: hulation.v1.badactor.ListAllowlistRequest
	(*ListAllowlistResponse)(nil),       // 10: hulation.v1.badactor.ListAllowlistResponse
	(*AddToAllowlistRequest)(nil),       // 11: hulation.v1.badactor.AddToAllowlistRequest
	(*AddToAllowlistResponse)(nil),      // 12: hulation.v1.badactor.AddToAllowlistResponse
	(*RemoveFromAllowlistRequest)(nil),  // 13: hulation.v1.badactor.RemoveFromAllowlistRequest
	(*RemoveFromAllowlistResponse)(nil), // 14: hulation.v1.badactor.RemoveFromAllowlistResponse
	(*BadActorStatsRequest)(nil),        // 15: hulation.v1.badactor.BadActorStatsRequest
	(*BadActorStatsResponse)(nil),       // 16: hulation.v1.badactor.BadActorStatsResponse
	(*StatBucket)(nil),                  // 17: hulation.v1.badactor.StatBucket
	(*ListSignaturesRequest)(nil),       // 18: hulation.v1.badactor.ListSignaturesRequest
	(*ListSignaturesResponse)(nil),      // 19: hulation.v1.badactor.ListSignaturesResponse
	(*timestamppb.Timestamp)(nil),       // 20: google.protobuf.Timestamp
}
var file_pkg_apispec_v1_badactor_badactor_proto_depIdxs = []int32{
	20, // 0: hulation.v1.badactor.BadActor.first_seen:type_name -> google.protobuf.Timestamp
	20, // 1: hulation.v1.badactor.BadActor.last_seen:type_name -> google.protobuf.Timestamp
	20, // 2: hulation.v1.badactor.AllowlistEntry.added_at:type_name -> google.protobuf.Timestamp
	0,  // 3: hulation.v1.badactor.ListBadActorsResponse.actors:type_name -> hulation.v1.badactor.BadActor
	0,  // 4: hulation.v1.badactor.ManualBlockResponse.actor:type_name -> hulation.v1.badactor.BadActor
	1,  // 5: hulation.v1.badactor.ListAllowlistResponse.entries:type_name -> hulation.v1.badactor.AllowlistEntry
	1,  // 6: hulation.v1.badactor.AddToAllowlistResponse.entry:type_name -> hulation.v1.badactor.AllowlistEntry
	17, // 7: hulation.v1.badactor.BadActorStatsResponse.top_sources_24h:type_name -> hulation.v1.badactor.StatBucket
	2,  // 8: hulation.v1.badactor.ListSignaturesResponse.signatures:type_name -> hulation.v1.badactor.Signature
	3,  // 9: hulation.v1.badactor.BadActorService.ListBadActors:input_type -> hulation.v1.badactor.ListBadActorsRequest
	5,  // 10: hulation.v1.badactor.BadActorService.ManualBlock:input_type -> hulation.v1.badactor.ManualBlockRequest
	7,  // 11: hulation.v1.badactor.BadActorService.EvictBadActor:input_type -> hulation.v1.badactor.EvictBadActorRequest
	9,  // 12: hulation.v1.badactor.BadActorService.ListAllowlist:input_type -> hulation.v1.badactor.ListAllowlistRequest
	11, // 13: hulation.v1.badactor.BadActorService.AddToAllowlist:input_type -> hulation.v1.badactor.AddToAllowlistRequest
	13, // 14: hulation.v1.badactor.BadActorService.RemoveFromAllowlist:input_type -> hulation.v1.badactor.RemoveFromAllowlistRequest
	15, // 15: hulation.v1.badactor.BadActorService.BadActorStats:input_type -> hulation.v1.badactor.BadActorStatsRequest
	18, // 16: hulation.v1.badactor.BadActorService.ListSignatures:input_type -> hulation.v1.badactor.ListSignaturesRequest
	4,  // 17: hulation.v1.badactor.BadActorService.ListBadActors:output_type -> hulation.v1.badactor.ListBadActorsResponse
	6,  // 18: hulation.v1.badactor.BadActorService.ManualBlock:output_type -> hulation.v1.badactor.ManualBlockResponse
	8,  // 19: hulation.v1.badactor.BadActorService.EvictBadActor:output_type -> hulation.v1.badactor.EvictBadActorResponse
	10, // 20: hulation.v1.badactor.BadActorService.ListAllowlist:output_type -> hulation.v1.badactor.ListAllowlistResponse
	12, // 21: hulation.v1.badactor.BadActorService.AddToAllowlist:output_type -> hulation.v1.badactor.AddToAllowlistResponse
	14, // 22: hulation.v1.badactor.BadActorService.RemoveFromAllowlist:output_type -> hulation.v1.badactor.RemoveFromAllowlistResponse
	16, // 23: hulation.v1.badactor.BadActorService.BadActorStats:output_type -> hulation.v1.badactor.BadActorStatsResponse
	19, // 24: hulation.v1.badactor.BadActorService.ListSignatures:output_type -> hulation.v1.badactor.ListSignaturesResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_apispec_v1_badactor_badactor_proto_init() }
func file_pkg_apispec_v1_badactor_badactor_proto_init() {
	if File_pkg_apispec_v1_badactor_badactor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_badactor_badactor_proto_rawDesc), len(file_pkg_apispec_v1_badactor_badactor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apispec_v1_badactor_badactor_proto_goTypes,
		DependencyIndexes: file_pkg_apispec_v1_badactor_badactor_proto_depIdxs,
		MessageInfos:      file_pkg_apispec_v1_badactor_badactor_proto_msgTypes,
	}.Build()
	File_pkg_apispec_v1_badactor_badactor_proto = out.File
	file_pkg_apispec_v1_badactor_badactor_proto_goTypes = nil
	file_pkg_apispec_v1_badactor_badactor_proto_depIdxs = nil
}
