// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: pkg/apispec/v1/landers/landers.proto

// LandersService — CRUD for landing-page tracking records on a virtual server.

package landersspec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LandersService_CreateLander_FullMethodName = "/hulation.v1.landers.LandersService/CreateLander"
	LandersService_ModifyLander_FullMethodName = "/hulation.v1.landers.LandersService/ModifyLander"
	LandersService_DeleteLander_FullMethodName = "/hulation.v1.landers.LandersService/DeleteLander"
	LandersService_ListLanders_FullMethodName  = "/hulation.v1.landers.LandersService/ListLanders"
	LandersService_GetLander_FullMethodName    = "/hulation.v1.landers.LandersService/GetLander"
)

// LandersServiceClient is the client API for LandersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LandersServiceClient interface {
	CreateLander(ctx context.Context, in *CreateLanderRequest, opts ...grpc.CallOption) (*CreateLanderResponse, error)
	ModifyLander(ctx context.Context, in *ModifyLanderRequest, opts ...grpc.CallOption) (*ModifyLanderResponse, error)
	DeleteLander(ctx context.Context, in *DeleteLanderRequest, opts ...grpc.CallOption) (*DeleteLanderResponse, error)
	ListLanders(ctx context.Context, in *ListLandersRequest, opts ...grpc.CallOption) (*ListLandersResponse, error)
	GetLander(ctx context.Context, in *GetLanderRequest, opts ...grpc.CallOption) (*GetLanderResponse, error)
}

type landersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLandersServiceClient(cc grpc.ClientConnInterface) LandersServiceClient {
	return &landersServiceClient{cc}
}

func (c *landersServiceClient) CreateLander(ctx context.Context, in *CreateLanderRequest, opts ...grpc.CallOption) (*CreateLanderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLanderResponse)
	err := c.cc.Invoke(ctx, LandersService_CreateLander_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landersServiceClient) ModifyLander(ctx context.Context, in *ModifyLanderRequest, opts ...grpc.CallOption) (*ModifyLanderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyLanderResponse)
	err := c.cc.Invoke(ctx, LandersService_ModifyLander_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landersServiceClient) DeleteLander(ctx context.Context, in *DeleteLanderRequest, opts ...grpc.CallOption) (*DeleteLanderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLanderResponse)
	err := c.cc.Invoke(ctx, LandersService_DeleteLander_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landersServiceClient) ListLanders(ctx context.Context, in *ListLandersRequest, opts ...grpc.CallOption) (*ListLandersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLandersResponse)
	err := c.cc.Invoke(ctx, LandersService_ListLanders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landersServiceClient) GetLander(ctx context.Context, in *GetLanderRequest, opts ...grpc.CallOption) (*GetLanderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLanderResponse)
	err := c.cc.Invoke(ctx, LandersService_GetLander_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LandersServiceServer is the server API for LandersService service.
// All implementations must embed UnimplementedLandersServiceServer
// for forward compatibility.
type LandersServiceServer interface {
	CreateLander(context.Context, *CreateLanderRequest) (*CreateLanderResponse, error)
	ModifyLander(context.Context, *ModifyLanderRequest) (*ModifyLanderResponse, error)
	DeleteLander(context.Context, *DeleteLanderRequest) (*DeleteLanderResponse, error)
	ListLanders(context.Context, *ListLandersRequest) (*ListLandersResponse, error)
	GetLander(context.Context, *GetLanderRequest) (*GetLanderResponse, error)
	mustEmbedUnimplementedLandersServiceServer()
}

// UnimplementedLandersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLandersServiceServer struct{}

func (UnimplementedLandersServiceServer) CreateLander(context.Context, *CreateLanderRequest) (*CreateLanderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLander not implemented")
}
func (UnimplementedLandersServiceServer) ModifyLander(context.Context, *ModifyLanderRequest) (*ModifyLanderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyLander not implemented")
}
func (UnimplementedLandersServiceServer) DeleteLander(context.Context, *DeleteLanderRequest) (*DeleteLanderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLander not implemented")
}
func (UnimplementedLandersServiceServer) ListLanders(context.Context, *ListLandersRequest) (*ListLandersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLanders not implemented")
}
func (UnimplementedLandersServiceServer) GetLander(context.Context, *GetLanderRequest) (*GetLanderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLander not implemented")
}
func (UnimplementedLandersServiceServer) mustEmbedUnimplementedLandersServiceServer() {}
func (UnimplementedLandersServiceServer) testEmbeddedByValue()                        {}

// UnsafeLandersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LandersServiceServer will
// result in compilation errors.
type UnsafeLandersServiceServer interface {
	mustEmbedUnimplementedLandersServiceServer()
}

func RegisterLandersServiceServer(s grpc.ServiceRegistrar, srv LandersServiceServer) {
	// If the following call pancis, it indicates UnimplementedLandersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LandersService_ServiceDesc, srv)
}

func _LandersService_CreateLander_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLanderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandersServiceServer).CreateLander(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LandersService_CreateLander_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandersServiceServer).CreateLander(ctx, req.(*CreateLanderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandersService_ModifyLander_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyLanderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandersServiceServer).ModifyLander(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LandersService_ModifyLander_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandersServiceServer).ModifyLander(ctx, req.(*ModifyLanderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandersService_DeleteLander_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLanderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandersServiceServer).DeleteLander(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LandersService_DeleteLander_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandersServiceServer).DeleteLander(ctx, req.(*DeleteLanderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandersService_ListLanders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLandersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandersServiceServer).ListLanders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LandersService_ListLanders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandersServiceServer).ListLanders(ctx, req.(*ListLandersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandersService_GetLander_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLanderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandersServiceServer).GetLander(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LandersService_GetLander_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandersServiceServer).GetLander(ctx, req.(*GetLanderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LandersService_ServiceDesc is the grpc.ServiceDesc for LandersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LandersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hulation.v1.landers.LandersService",
	HandlerType: (*LandersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLander",
			Handler:    _LandersService_CreateLander_Handler,
		},
		{
			MethodName: "ModifyLander",
			Handler:    _LandersService_ModifyLander_Handler,
		},
		{
			MethodName: "DeleteLander",
			Handler:    _LandersService_DeleteLander_Handler,
		},
		{
			MethodName: "ListLanders",
			Handler:    _LandersService_ListLanders_Handler,
		},
		{
			MethodName: "GetLander",
			Handler:    _LandersService_GetLander_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apispec/v1/landers/landers.proto",
}
