// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/apispec/v1/forms/forms.proto

// FormsService — CRUD for forms hosted on a virtual server.

package formsspec

import (
	_ "github.com/tlalocweb/hulation/pkg/server/authware/proto"
	_ "github.com/tlalocweb/hulation/protoext/izuma/auth"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldDefinition describes a single input in a form's schema.
type FieldDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type one of: text, email, number, tel, url, textarea, select, checkbox, radio, hidden
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required    bool   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Label       string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Placeholder string `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	// options populate select/radio inputs.
	Options []string `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	// regex is an optional validation pattern.
	Regex         string `protobuf:"bytes,7,opt,name=regex,proto3" json:"regex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDefinition) Reset() {
	*x = FieldDefinition{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDefinition) ProtoMessage() {}

func (x *FieldDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDefinition.ProtoReflect.Descriptor instead.
func (*FieldDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{0}
}

func (x *FieldDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldDefinition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FieldDefinition) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *FieldDefinition) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FieldDefinition) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

// Form is the form configuration payload.
type Form struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId    string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Fields      []*FieldDefinition     `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	// redirect_url is where the browser is sent after a successful submission.
	RedirectUrl string `protobuf:"bytes,6,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	// email_notify_to — comma-separated recipients for submission notifications.
	EmailNotifyTo string                 `protobuf:"bytes,7,opt,name=email_notify_to,json=emailNotifyTo,proto3" json:"email_notify_to,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Form) Reset() {
	*x = Form{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Form) ProtoMessage() {}

func (x *Form) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Form.ProtoReflect.Descriptor instead.
func (*Form) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{1}
}

func (x *Form) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Form) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Form) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Form) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Form) GetFields() []*FieldDefinition {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Form) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *Form) GetEmailNotifyTo() string {
	if x != nil {
		return x.EmailNotifyTo
	}
	return ""
}

func (x *Form) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Form) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Form          *Form                  `protobuf:"bytes,2,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFormRequest) Reset() {
	*x = CreateFormRequest{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormRequest) ProtoMessage() {}

func (x *CreateFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormRequest.ProtoReflect.Descriptor instead.
func (*CreateFormRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFormRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateFormRequest) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type CreateFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFormResponse) Reset() {
	*x = CreateFormResponse{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormResponse) ProtoMessage() {}

func (x *CreateFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormResponse.ProtoReflect.Descriptor instead.
func (*CreateFormResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type ModifyFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	FormId        string                 `protobuf:"bytes,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Form          *Form                  `protobuf:"bytes,3,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyFormRequest) Reset() {
	*x = ModifyFormRequest{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyFormRequest) ProtoMessage() {}

func (x *ModifyFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyFormRequest.ProtoReflect.Descriptor instead.
func (*ModifyFormRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyFormRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ModifyFormRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *ModifyFormRequest) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type ModifyFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyFormResponse) Reset() {
	*x = ModifyFormResponse{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyFormResponse) ProtoMessage() {}

func (x *ModifyFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyFormResponse.ProtoReflect.Descriptor instead.
func (*ModifyFormResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{5}
}

func (x *ModifyFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type DeleteFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	FormId        string                 `protobuf:"bytes,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormRequest) Reset() {
	*x = DeleteFormRequest{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormRequest) ProtoMessage() {}

func (x *DeleteFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormRequest.ProtoReflect.Descriptor instead.
func (*DeleteFormRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFormRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteFormRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

type DeleteFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormResponse) Reset() {
	*x = DeleteFormResponse{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormResponse) ProtoMessage() {}

func (x *DeleteFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormResponse.ProtoReflect.Descriptor instead.
func (*DeleteFormResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFormResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListFormsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormsRequest) Reset() {
	*x = ListFormsRequest{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormsRequest) ProtoMessage() {}

func (x *ListFormsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormsRequest.ProtoReflect.Descriptor instead.
func (*ListFormsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{8}
}

func (x *ListFormsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ListFormsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forms         []*Form                `protobuf:"bytes,1,rep,name=forms,proto3" json:"forms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormsResponse) Reset() {
	*x = ListFormsResponse{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormsResponse) ProtoMessage() {}

func (x *ListFormsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormsResponse.ProtoReflect.Descriptor instead.
func (*ListFormsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{9}
}

func (x *ListFormsResponse) GetForms() []*Form {
	if x != nil {
		return x.Forms
	}
	return nil
}

type GetFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	FormId        string                 `protobuf:"bytes,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormRequest) Reset() {
	*x = GetFormRequest{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormRequest) ProtoMessage() {}

func (x *GetFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormRequest.ProtoReflect.Descriptor instead.
func (*GetFormRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{10}
}

func (x *GetFormRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetFormRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

type GetFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormResponse) Reset() {
	*x = GetFormResponse{}
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormResponse) ProtoMessage() {}

func (x *GetFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apispec_v1_forms_forms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormResponse.ProtoReflect.Descriptor instead.
func (*GetFormResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP(), []int{11}
}

func (x *GetFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

var File_pkg_apispec_v1_forms_forms_proto protoreflect.FileDescriptor

const file_pkg_apispec_v1_forms_forms_proto_rawDesc = "" +
	"\n" +
	" pkg/apispec/v1/forms/forms.proto\x12\x11hulation.v1.forms\x1a\x1cgoogle/api/annotations.proto\x1a\x1bizuma/auth/permission.proto\x1a+pkg/server/authware/proto/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x01\n" +
	"\x0fFieldDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x05 \x01(\tR\vplaceholder\x12\x18\n" +
	"\aoptions\x18\x06 \x03(\tR\aoptions\x12\x14\n" +
	"\x05regex\x18\a \x01(\tR\x05regex\"\xe6\x02\n" +
	"\x04Form\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12:\n" +
	"\x06fields\x18\x05 \x03(\v2\".hulation.v1.forms.FieldDefinitionR\x06fields\x12!\n" +
	"\fredirect_url\x18\x06 \x01(\tR\vredirectUrl\x12&\n" +
	"\x0femail_notify_to\x18\a \x01(\tR\remailNotifyTo\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"]\n" +
	"\x11CreateFormRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12+\n" +
	"\x04form\x18\x02 \x01(\v2\x17.hulation.v1.forms.FormR\x04form\"A\n" +
	"\x12CreateFormResponse\x12+\n" +
	"\x04form\x18\x01 \x01(\v2\x17.hulation.v1.forms.FormR\x04form\"v\n" +
	"\x11ModifyFormRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\aform_id\x18\x02 \x01(\tR\x06formId\x12+\n" +
	"\x04form\x18\x03 \x01(\v2\x17.hulation.v1.forms.FormR\x04form\"A\n" +
	"\x12ModifyFormResponse\x12+\n" +
	"\x04form\x18\x01 \x01(\v2\x17.hulation.v1.forms.FormR\x04form\"I\n" +
	"\x11DeleteFormRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\aform_id\x18\x02 \x01(\tR\x06formId\"$\n" +
	"\x12DeleteFormResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"/\n" +
	"\x10ListFormsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"B\n" +
	"\x11ListFormsResponse\x12-\n" +
	"\x05forms\x18\x01 \x03(\v2\x17.hulation.v1.forms.FormR\x05forms\"F\n" +
	"\x0eGetFormRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\aform_id\x18\x02 \x01(\tR\x06formId\">\n" +
	"\x0fGetFormResponse\x12+\n" +
	"\x04form\x18\x01 \x01(\v2\x17.hulation.v1.forms.FormR\x04form2\xd6\x06\n" +
	"\fFormsService\x12\xa4\x01\n" +
	"\n" +
	"CreateForm\x12$.hulation.v1.forms.CreateFormRequest\x1a%.hulation.v1.forms.CreateFormResponse\"Iҵ\x18!\n" +
	"\x1fserver.{server_id}.forms.create\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/forms/{server_id}\x12\xae\x01\n" +
	"\n" +
	"ModifyForm\x12$.hulation.v1.forms.ModifyFormRequest\x1a%.hulation.v1.forms.ModifyFormResponse\"Sҵ\x18!\n" +
	"\x1fserver.{server_id}.forms.modify\x82\xd3\xe4\x93\x02(:\x01*2#/api/v1/forms/{server_id}/{form_id}\x12\xab\x01\n" +
	"\n" +
	"DeleteForm\x12$.hulation.v1.forms.DeleteFormRequest\x1a%.hulation.v1.forms.DeleteFormResponse\"Pҵ\x18!\n" +
	"\x1fserver.{server_id}.forms.delete\x82\xd3\xe4\x93\x02%*#/api/v1/forms/{server_id}/{form_id}\x12\x9c\x01\n" +
	"\tListForms\x12#.hulation.v1.forms.ListFormsRequest\x1a$.hulation.v1.forms.ListFormsResponse\"Dҵ\x18\x1f\n" +
	"\x1dserver.{server_id}.forms.list\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/forms/{server_id}\x12\xa0\x01\n" +
	"\aGetForm\x12!.hulation.v1.forms.GetFormRequest\x1a\".hulation.v1.forms.GetFormResponse\"Nҵ\x18\x1f\n" +
	"\x1dserver.{server_id}.forms.read\x82\xd3\xe4\x93\x02%\x12#/api/v1/forms/{server_id}/{form_id}B>Z<github.com/tlalocweb/hulation/pkg/apispec/v1/forms;formsspecb\x06proto3"

var (
	file_pkg_apispec_v1_forms_forms_proto_rawDescOnce sync.Once
	file_pkg_apispec_v1_forms_forms_proto_rawDescData []byte
)

func file_pkg_apispec_v1_forms_forms_proto_rawDescGZIP() []byte {
	file_pkg_apispec_v1_forms_forms_proto_rawDescOnce.Do(func() {
		file_pkg_apispec_v1_forms_forms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_forms_forms_proto_rawDesc), len(file_pkg_apispec_v1_forms_forms_proto_rawDesc)))
	})
	return file_pkg_apispec_v1_forms_forms_proto_rawDescData
}

var file_pkg_apispec_v1_forms_forms_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_apispec_v1_forms_forms_proto_goTypes = []any{
	(*FieldDefinition)(nil),       // 0: hulation.v1.forms.FieldDefinition
	(*Form)(nil),                  // 1: hulation.v1.forms.Form
	(*CreateFormRequest)(nil),     // 2: hulation.v1.forms.CreateFormRequest
	(*CreateFormResponse)(nil),    // 3: hulation.v1.forms.CreateFormResponse
	(*ModifyFormRequest)(nil),     // 4: hulation.v1.forms.ModifyFormRequest
	(*ModifyFormResponse)(nil),    // 5: hulation.v1.forms.ModifyFormResponse
	(*DeleteFormRequest)(nil),     // 6: hulation.v1.forms.DeleteFormRequest
	(*DeleteFormResponse)(nil),    // 7: hulation.v1.forms.DeleteFormResponse
	(*ListFormsRequest)(nil),      // 8: hulation.v1.forms.ListFormsRequest
	(*ListFormsResponse)(nil),     // 9: hulation.v1.forms.ListFormsResponse
	(*GetFormRequest)(nil),        // 10: hulation.v1.forms.GetFormRequest
	(*GetFormResponse)(nil),       // 11: hulation.v1.forms.GetFormResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_pkg_apispec_v1_forms_forms_proto_depIdxs = []int32{
	0,  // 0: hulation.v1.forms.Form.fields:type_name -> hulation.v1.forms.FieldDefinition
	12, // 1: hulation.v1.forms.Form.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: hulation.v1.forms.Form.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: hulation.v1.forms.CreateFormRequest.form:type_name -> hulation.v1.forms.Form
	1,  // 4: hulation.v1.forms.CreateFormResponse.form:type_name -> hulation.v1.forms.Form
	1,  // 5: hulation.v1.forms.ModifyFormRequest.form:type_name -> hulation.v1.forms.Form
	1,  // 6: hulation.v1.forms.ModifyFormResponse.form:type_name -> hulation.v1.forms.Form
	1,  // 7: hulation.v1.forms.ListFormsResponse.forms:type_name -> hulation.v1.forms.Form
	1,  // 8: hulation.v1.forms.GetFormResponse.form:type_name -> hulation.v1.forms.Form
	2,  // 9: hulation.v1.forms.FormsService.CreateForm:input_type -> hulation.v1.forms.CreateFormRequest
	4,  // 10: hulation.v1.forms.FormsService.ModifyForm:input_type -> hulation.v1.forms.ModifyFormRequest
	6,  // 11: hulation.v1.forms.FormsService.DeleteForm:input_type -> hulation.v1.forms.DeleteFormRequest
	8,  // 12: hulation.v1.forms.FormsService.ListForms:input_type -> hulation.v1.forms.ListFormsRequest
	10, // 13: hulation.v1.forms.FormsService.GetForm:input_type -> hulation.v1.forms.GetFormRequest
	3,  // 14: hulation.v1.forms.FormsService.CreateForm:output_type -> hulation.v1.forms.CreateFormResponse
	5,  // 15: hulation.v1.forms.FormsService.ModifyForm:output_type -> hulation.v1.forms.ModifyFormResponse
	7,  // 16: hulation.v1.forms.FormsService.DeleteForm:output_type -> hulation.v1.forms.DeleteFormResponse
	9,  // 17: hulation.v1.forms.FormsService.ListForms:output_type -> hulation.v1.forms.ListFormsResponse
	11, // 18: hulation.v1.forms.FormsService.GetForm:output_type -> hulation.v1.forms.GetFormResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_apispec_v1_forms_forms_proto_init() }
func file_pkg_apispec_v1_forms_forms_proto_init() {
	if File_pkg_apispec_v1_forms_forms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apispec_v1_forms_forms_proto_rawDesc), len(file_pkg_apispec_v1_forms_forms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apispec_v1_forms_forms_proto_goTypes,
		DependencyIndexes: file_pkg_apispec_v1_forms_forms_proto_depIdxs,
		MessageInfos:      file_pkg_apispec_v1_forms_forms_proto_msgTypes,
	}.Build()
	File_pkg_apispec_v1_forms_forms_proto = out.File
	file_pkg_apispec_v1_forms_forms_proto_goTypes = nil
	file_pkg_apispec_v1_forms_forms_proto_depIdxs = nil
}
