name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        path: hulation

    - uses: actions/checkout@v4
      with:
        repository: tlalocweb/clickhouse
        path: clickhouse

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache-dependency-path: hulation/go.sum

    - name: Build
      run: cd hulation && go build -v .

#    - name: Test
#      run: cd hulation && go test ./utils/... ./hooks/... -v
